### PR TITLE
MockETagManager is now thread safe

### LINKED ISSUE #945: MockETagManager is not thread safe, which results in random test failures
This likely only happens when running tests in parallel. Here's the stack trace:
Screen Shot 2021-11-15 at 14 21 04

And the race condition is here:
Screen Shot 2021-11-15 at 14 21 47

Because `HTTPClient` uses `ETagManager` from a background thread. I see that `ETagManager` itself uses an `NSRecursiveLock`, but `MockETagManager` isn't thread safe.

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #945.

I really like https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Atomic.swift, but I think this is a good solution for now.

### CODE REVIEW

File: Purchases/Misc/Lock.swift [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+internal final class Lock {
+    
+    private let recursiveLock = NSRecursiveLock()
+
+    @discardableResult
+    func perform<T>(_ block: () -> T) -> T {
+        recursiveLock.lock()
+        defer { recursiveLock.unlock() }
+
+        return block()
```
Comment (vegaro) [inline Purchases/Misc/Lock.swift:25]: beautiful

**Review by vegaro — APPROVED** [review]

File: Purchases/Misc/Lock.swift (hunk 1 above)
Comment (taquitos) [reply Purchases/Misc/Lock.swift:25]: 😍

**Comment by taquitos** [comment]
> Fixes #945.
> 
> I really like https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Atomic.swift, but I think this is a good solution for now.

I was going to mention the Swift implications of using `os_unfair_lock`, but reading through `Atomic.swift`, that implementation uses it while working around the relocating issues, so that's clever.
