### PR TITLE
`ReceiptFetcher`: throttle receipt refreshing to avoid `StoreKit` throttle errors

### LINKED ISSUE #2116: Error in first call, the user tries to purchase a product
- [ ] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Lastly, we're dealing with a first error thrown when we want to purchase something. The first time it throws a throttling error and the second time (not even a second after) the purchase works correctly.

What do we see? -> The purchase is canceled without the system sheet to pay is shown.

1. Environment
   1. Platform: iOS 
   2. SDK version: 3.14.3
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N): N
   4. OS version: 15.x, 16.x
   5. Xcode version: 14.3.1
   6. How widespread is the issue. Percentage of devices affected: Affects on App Store review, it is not demonstrated to happen in production. 
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```logs
2022-12-03 12:31:51.715719+0100 app[673:61074] [Purchases] - DEBUG: 👤 Identifying App User ID
2022-12-03 12:31:51.732816+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Debug logging enabled
2022-12-03 12:31:51.733040+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ SDK Version - 4.14.3
2022-12-03 12:31:51.733215+0100 app[673:61074] [Purchases] - DEBUG: 👤 Initial App User ID set
2022-12-03 12:31:51.747630+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ setting reserved attribute: $AppInstanceId
2022-12-03 12:31:51.752473+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Delegate set
2022-12-03 12:31:51.776111+0100 app[673:61074] [APP] <RCPurchases: 0x280237a00>, info <CustomerInfo:
originalApplicationVersion=1.0,
latestExpirationDate=Optional(2022-12-03 00:49:22 +0000),
activeEntitlements=["all access": "<EntitlementInfo: \"\nidentifier=all access,\nisActive=true,\nwillRenew=true,\nperiodType=PeriodType(rawValue: 0),\nlatestPurchaseDate=Optional(2022-12-02 23:49:22 +0000),\noriginalPurchaseDate=Optional(2022-04-27 18:47:44 +0000),\nexpirationDate=Optional(2022-12-03 00:49:22 +0000),\nstore=Store(rawValue: 0),\nproductIdentifier=product2,\nisSandbox=true,\nunsubscribeDetectedAt=nil,\nbillingIssueDetectedAt=nil,\nownershipType=PurchaseOwnershipType(rawValue: 0)\n>"],
activeSubscriptions=["product2": "expiresDate: Optional(2022-12-03 00:49:22 +0000)"],
nonSubscriptions=[],
requestDate=2022-12-03 00:01:13 +0000,
firstSeen=2022-11-29 16:21:17 +0000,
originalAppUserId=$RCAnonymousID:35d8410f48c144fd8fb8a6ec17ee858a,
entitlements=["counseling": "<EntitlementInfo: \"\nidentifier=counseling,\nisActive=false,\nwillRenew=false,\nperiodType=PeriodType(rawValue: 0),\nlatestPurchaseDate=Optional(2022-11-06 17:30:38 +0000),\noriginalPurchaseDate=Optional(2022-10-09 17:30:38 +0000),\nexpirationDate=Optional(2022-11-10 09:02:06 +0000),\nstore=Store(rawValue: 3),\nproductIdentifier=prod_LCWjS9AccWbDa8,\nisSandbox=true,\nunsubscribeDetectedAt=Optional(2022-11-10 09:02:06 +0000),\nbillingIssueDetectedAt=Optional(2022-11-10 09:02:07 +0000),\nownershipType=PurchaseOwnershipType(rawValue: 0)\n>", "all access": "<EntitlementInfo: \"\nidentifier=all access,\nisActive=true,\nwillRenew=true,\nperiodType=PeriodType(rawValue: 0),\nlatestPurchaseDate=Optional(2022-12-02 23:49:22 +0000),\noriginalPurchaseDate=Optional(2022-04-27 18:47:44 +0000),\nexpirationDate=Optional(2022-12-03 00:49:22 +0000),\nstore=Store(rawValue: 0),\nproductIdentifier=product2,\nisSandbox=true,\nunsubscribeDetectedAt=nil,\nbillingIssueDetectedAt=nil,\nownershipType=PurchaseOwnershipType(rawValue: 0)\n>"]
>
2022-12-03 12:31:51.961806+0100 app[673:61348] [Purchases] - WARN: ⚠️ The appUserID passed to logIn is the same as the one already cached. No action will be taken.
2022-12-03 12:31:51.965182+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:51.965444+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ GetCustomerInfoOperation: Started
2022-12-03 12:31:51.966732+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request GET subscribers/Subscriber
2022-12-03 12:31:51.968417+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ applicationDidBecomeActive
2022-12-03 12:31:51.971978+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
2022-12-03 12:31:51.972199+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Offerings cache is stale, updating caches
2022-12-03 12:31:51.974494+0100 app[673:61347] [Purchases] - DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:51.974658+0100 app[673:61347] [Purchases] - DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:51.975334+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:51.976804+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
2022-12-03 12:31:51.978127+0100 app[673:61346] [Purchases] - DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:51.979110+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:51.984649+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
2022-12-03 12:31:51.984797+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ API request started: GET /v1/subscribers/Subscriber
2022-12-03 12:31:51.985540+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:52.003341+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
2022-12-03 12:31:52.003519+0100 app[673:61345] [Purchases] - DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:52.054007+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:52.056793+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
2022-12-03 12:31:52.057011+0100 app[673:61346] [Purchases] - DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:52.100764+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:52.103258+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
2022-12-03 12:31:52.103535+0100 app[673:61358] [Purchases] - DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:52.103773+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:57.323171+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ API request completed: GET /v1/subscribers/Subscriber 200
2022-12-03 12:31:57.355404+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Sending latest CustomerInfo to delegate.
2022-12-03 12:31:57.355474+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.355815+0100 app[673:61074] <RCPurchases: 0x280237a00>, info <CustomerInfo:
originalApplicationVersion=1.0,
latestExpirationDate=Optional(2022-12-03 09:49:46 +0000),
activeEntitlements=[:],
activeSubscriptions=[:],
nonSubscriptions=[],
requestDate=2022-12-03 11:31:57 +0000,
firstSeen=2022-11-29 16:21:17 +0000,
originalAppUserId=$RCAnonymousID:35d8410f48c144fd8fb8a6ec17ee858a,
entitlements=["all access": "<EntitlementInfo: \"\nidentifier=all access,\nisActive=false,\nwillRenew=false,\nperiodType=PeriodType(rawValue: 0),\nlatestPurchaseDate=Optional(2022-12-03 08:49:46 +0000),\noriginalPurchaseDate=Optional(2022-04-27 18:47:44 +0000),\nexpirationDate=Optional(2022-12-03 09:49:46 +0000),\nstore=Store(rawValue: 0),\nproductIdentifier=product2,\nisSandbox=true,\nunsubscribeDetectedAt=Optional(2022-12-03 09:58:57 +0000),\nbillingIssueDetectedAt=nil,\nownershipType=PurchaseOwnershipType(rawValue: 0)\n>", "counseling": "<EntitlementInfo: \"\nidentifier=counseling,\nisActive=false,\nwillRenew=false,\nperiodType=PeriodType(rawValue: 0),\nlatestPurchaseDate=Optional(2022-11-06 17:30:38 +0000),\noriginalPurchaseDate=Optional(2022-10-09 17:30:38 +0000),\nexpirationDate=Optional(2022-11-10 09:02:06 +0000),\nstore=Store(rawValue: 3),\nproductIdentifier=prod_LCWjS9AccWbDa8,\nisSandbox=true,\nunsubscribeDetectedAt=Optional(2022-11-10 09:02:06 +0000),\nbillingIssueDetectedAt=Optional(2022-11-10 09:02:07 +0000),\nownershipType=PurchaseOwnershipType(rawValue: 0)\n>"]
>
2022-12-03 12:31:57.357311+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.357572+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:57.359567+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.372051+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.373064+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:31:57.373565+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.376482+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.379486+0100 app[673:61351] [Purchases] - DEBUG: 😻 CustomerInfo updated from network.
2022-12-03 12:31:57.379575+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ GetCustomerInfoOperation: Finished
2022-12-03 12:31:57.379812+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Serial request done: GET subscribers/Subscriber, 0 requests left in the queue
2022-12-03 12:31:57.379824+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ GetOfferingsOperation: Started
2022-12-03 12:31:57.380114+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request GET subscribers/Subscriber/offerings
2022-12-03 12:31:57.382433+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ API request started: GET /v1/subscribers/Subscriber/offerings
2022-12-03 12:31:57.386183+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ No cached Offerings, fetching from network
2022-12-03 12:31:57.386387+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:31:57.505988+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ API request completed: GET /v1/subscribers/Subscriber/offerings 304
2022-12-03 12:31:57.511901+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ No existing products cached, starting store products request for: ["product1", "product2", "product4", "product3"]
2022-12-03 12:31:57.512409+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product3", "product4", "product2", "product1"], appending to completion
2022-12-03 12:31:57.512475+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product4", "product1", "product2", "product3"], appending to completion
2022-12-03 12:31:57.512474+0100 app[673:61339] [Purchases] - DEBUG: ℹ️ No existing products cached, starting store products request for: ["product1", "product2", "product4", "product3"]
2022-12-03 12:31:57.512521+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product4", "product1", "product2", "product3"], appending to completion
2022-12-03 12:31:57.512647+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ GetOfferingsOperation: Finished
2022-12-03 12:31:57.512854+0100 app[673:61351] [Purchases] - DEBUG: ℹ️ Serial request done: GET subscribers/Subscriber/offerings, 0 requests left in the queue
2022-12-03 12:31:58.121134+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218313433 2000000042575785 1
2022-12-03 12:31:58.131405+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.131483+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218320027 2000000042575785 1
2022-12-03 12:31:58.135102+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.135345+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218327443 2000000042575785 1
2022-12-03 12:31:58.142853+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.142932+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218334901 2000000042575785 1
2022-12-03 12:31:58.148025+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.148102+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218342186 2000000042575785 1
2022-12-03 12:31:58.151957+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.152037+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218353996 2000000042575785 1
2022-12-03 12:31:58.155420+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.155685+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218362596 2000000042575785 1
2022-12-03 12:31:58.159132+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.162653+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218370255 2000000042575785 1
2022-12-03 12:31:58.165465+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.165597+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218377794 2000000042575785 1
2022-12-03 12:31:58.167519+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:31:58.670892+0100 app[673:61074] <SKReceiptRefreshRequest: 0x283edc860>: Finished refreshing receipt with error: Error Domain=ASDErrorDomain Code=603 "Request throttled" UserInfo={NSLocalizedFailureReason=Unified receipt is valid and current, NSLocalizedDescription=Request throttled, AMSServerErrorCode=0}
2022-12-03 12:31:58.671296+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.671367+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ No existing products cached, starting store products request for: ["product2"]
2022-12-03 12:31:58.671527+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.671584+0100 app[673:61341] [Purchases] - DEBUG: ℹ️ No existing products cached, starting store products request for: ["product2"]
2022-12-03 12:31:58.671586+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.671781+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.671916+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.672198+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.672251+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.672403+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.672641+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.672869+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.672955+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.673223+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.673338+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.673620+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.673873+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.674237+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.674313+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found an existing request for products: ["product2"], appending to completion
2022-12-03 12:31:58.868197+0100 app[673:61341] [Purchases] - DEBUG: 😻 Store products request finished
2022-12-03 12:31:58.868453+0100 app[673:61341] [Purchases] - DEBUG: 😻 Store products request request received response
2022-12-03 12:31:58.885519+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:31:58.885596+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Attempting to check intro eligibility locally
2022-12-03 12:31:58.910456+0100 app[673:61341] [Purchases] - DEBUG: 😻 Store products request finished
2022-12-03 12:31:58.910562+0100 app[673:61340] [Purchases] - DEBUG: 😻 Store products request request received response
2022-12-03 12:31:59.743410+0100 app[673:61339] ——
2022-12-03 12:31:59.976390+0100 app[673:61074] [Purchases] - INFO: ℹ️ Receipt parsed successfully
2022-12-03 12:31:59.977579+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Skipping products request for these products because they were already cached: ["product1", "product3", "product2"]
2022-12-03 12:31:59.979000+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Local intro eligibility computed locally. Result: ["product2": RevenueCat.IntroEligibilityStatus]
2022-12-03 12:31:59.981362+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.036750+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Started
2022-12-03 12:32:00.037078+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.109191+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.161989+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.162299+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.212993+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.213379+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.262242+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.262582+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.312178+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.312472+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.362974+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.363308+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.414729+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.415060+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:00.467348+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Network operation 'PostReceiptDataOperation' found with the same cache key 'Subscriber...'. Skipping request.
2022-12-03 12:32:00.568232+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ applicationDidBecomeActive
2022-12-03 12:32:00.572312+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:32:00.576136+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Vending CustomerInfo from cache.
2022-12-03 12:32:01.355364+0100 app[673:61348] [Purchases] - INFO: ℹ️ Receipt parsed successfully
2022-12-03 12:32:01.489184+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Posting receipt: {
  "opaque_value" : "3GbHdY+btd01j1hSfWFEfw==",
  "original_application_version" : "1.0",
  "bundle_id" : "app.app.company",
  "sha1_hash" : "T9Bfp2cXoltRTMsFGo6wWy+Enjk=",
  "application_version" : "72e87690",
  "creation_date" : "2022-12-03T11:31:57Z",
  "in_app_purchases" : [
    {
      "product_id" : "product1",
      "quantity" : 1,
      "transaction_id" : "2000000073582172",
      "is_in_trial_period" : true,
      "is_in_intro_offer_period" : false,
      "expires_date" : "2022-05-05T07:06:39Z",
      "web_order_line_item_id" : 2000000003509776,
      "original_purchase_date" : "2022-04-27T18:47:44Z",
      "original_transaction_id" : "2000000042575785",
      "product_type" : 3,
      "purchase_date" : "2022-05-05T07:03:39Z"
    },
    {
      "product_id" : "product2",
      "quantity" : 1,
      "transaction_id" : "2000000139167031",
      "is_in_trial_period" : false,
      "is_in_intro_offer_period"
2022-12-03 12:32:01.489811+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST receipts
2022-12-03 12:32:01.500700+0100 app[673:61348] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
———————————————
2022-12-03 12:32:03.858742+0100 app[673:61074] USER TAPPED BUY
2022-12-03 12:32:03.859899+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Skipping products request for these products because they were already cached: ["product2"]
2022-12-03 12:32:03.860228+0100 app[673:61074] [Purchases] - INFO: 💰 Purchasing Product 'product2'
2022-12-03 12:32:03.863805+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218313433 2000000042575785 1
2022-12-03 12:32:03.865744+0100 app[673:61339] -----
2022-12-03 12:32:03.868101+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
2022-12-03 12:32:04.317425+0100 app[673:61074] <SKReceiptRefreshRequest: 0x283ec02e0>: Finished refreshing receipt with error: Error Domain=ASDErrorDomain Code=603 "Request throttled" UserInfo={NSLocalizedFailureReason=Unified receipt is valid and current, NSLocalizedDescription=Request throttled, AMSServerErrorCode=0}
2022-12-03 12:32:04.317867+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
2022-12-03 12:32:04.317932+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Skipping products request for these products because they were already cached: ["product2"]
2022-12-03 12:32:04.318225+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: Subscriber
2022-12-03 12:32:10.031311+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ API request completed: POST /v1/receipts 429
2022-12-03 12:32:10.068450+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Finished
2022-12-03 12:32:10.068675+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ Serial request done: POST receipts, 0 requests left in the queue
2022-12-03 12:32:10.069132+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Started
2022-12-03 12:32:10.077360+0100 app[673:61074] [Purchases] - ERROR: 😿‼️ There was an unknown backend error. There is another request in flight trying to perform the same action.
2022-12-03 12:32:10.079421+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218313433' for product 'product2'
2022-12-03 12:32:10.082202+0100 app[673:61074] [Purchases] - ERROR: 💰 Product purchase for 'product2' failed with error: Error Domain=RevenueCat.ErrorCode Code=16 "There was an unknown backend error. There is another request in flight trying to perform the same action." UserInfo={source_function=convertUnsuccessfulResponseToError(), source_file=RevenueCat/HTTPClient.swift:378, NSUnderlyingError=0x2831b4210 {Error Domain=RevenueCat.BackendErrorCode Code=-1 "There is another request in flight trying to perform the same action." UserInfo={NSLocalizedDescription=There is another request in flight trying to perform the same action.}}, readable_error_code=UNKNOWN_BACKEND_ERROR, rc_response_status_code=429, NSLocalizedDescription=There was an unknown backend error. There is another request in flight trying to perform the same action.}
2022-12-03 12:32:10.623685+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218313433 2000000042575785 1
2022-12-03 12:32:11.075331+0100 app[673:61344] [Purchases] - INFO: ℹ️ Receipt parsed successfully
2022-12-03 12:32:11.176238+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Posting receipt: {
  "opaque_value" : "3GbHdY+btd01j1hSfWFEfw==",
  "original_application_version" : "1.0",
  "bundle_id" : "app.app.company",
  "sha1_hash" : "T9Bfp2cXoltRTMsFGo6wWy+Enjk=",
  "application_version" : "72e87690",
  "creation_date" : "2022-12-03T11:31:57Z",
  "in_app_purchases" : [
    {
      "product_id" : "product1",
      "quantity" : 1,
      "transaction_id" : "2000000073582172",
      "is_in_trial_period" : true,
      "is_in_intro_offer_period" : false,
      "expires_date" : "2022-05-05T07:06:39Z",
      "web_order_line_item_id" : 2000000003509776,
      "original_purchase_date" : "2022-04-27T18:47:44Z",
      "original_transaction_id" : "2000000042575785",
      "product_type" : 3,
      "purchase_date" : "2022-05-05T07:03:39Z"
    },
    {
      "product_id" : "product2",
      "quantity" : 1,
      "transaction_id" : "2000000139167031",
      "is_in_trial_period" : false,
      "is_in_intro_offer_period"
2022-12-03 12:32:11.177669+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST receipts
2022-12-03 12:32:11.196837+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
2022-12-03 12:32:18.138590+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ API request completed: POST /v1/receipts 200
2022-12-03 12:32:18.155775+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Finished
2022-12-03 12:32:18.155997+0100 app[673:61344] [Purchases] - DEBUG: ℹ️ Serial request done: POST receipts, 0 requests left in the queue
2022-12-03 12:32:18.156033+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Started
2022-12-03 12:32:18.158233+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218327443' for product 'product2'
2022-12-03 12:32:18.160518+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218342186' for product 'product2'
2022-12-03 12:32:18.162814+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218353996' for product 'product2'
2022-12-03 12:32:18.164401+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218362596' for product 'product2'
2022-12-03 12:32:18.165638+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218370255' for product 'product2'
2022-12-03 12:32:18.167233+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218334901' for product 'product2'
2022-12-03 12:32:18.169136+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218377794' for product 'product2'
2022-12-03 12:32:18.171156+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218320027' for product 'product2'
2022-12-03 12:32:18.738785+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218327443 2000000042575785 1
2022-12-03 12:32:18.740780+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218362596 2000000042575785 1
2022-12-03 12:32:18.750542+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218342186 2000000042575785 1
2022-12-03 12:32:18.765622+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218370255 2000000042575785 1
2022-12-03 12:32:18.765717+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218353996 2000000042575785 1
2022-12-03 12:32:19.250106+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218334901 2000000042575785 1
2022-12-03 12:32:19.253763+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218377794 2000000042575785 1
2022-12-03 12:32:19.262774+0100 app[673:61074] [Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: product2 2000000218320027 2000000042575785 1
2022-12-03 12:32:19.537491+0100 app[673:61340] [Purchases] - INFO: ℹ️ Receipt parsed successfully
2022-12-03 12:32:19.646079+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Posting receipt: {
  "opaque_value" : "3GbHdY+btd01j1hSfWFEfw==",
  "original_application_version" : "1.0",
  "bundle_id" : "app.app.company",
  "sha1_hash" : "T9Bfp2cXoltRTMsFGo6wWy+Enjk=",
  "application_version" : "72e87690",
  "creation_date" : "2022-12-03T11:31:57Z",
  "in_app_purchases" : [
    {
      "product_id" : "product1",
      "quantity" : 1,
      "transaction_id" : "2000000073582172",
      "is_in_trial_period" : true,
      "is_in_intro_offer_period" : false,
      "expires_date" : "2022-05-05T07:06:39Z",
      "web_order_line_item_id" : 2000000003509776,
      "original_purchase_date" : "2022-04-27T18:47:44Z",
      "original_transaction_id" : "2000000042575785",
      "product_type" : 3,
      "purchase_date" : "2022-05-05T07:03:39Z"
    },
    {
      "product_id" : "product2",
      "quantity" : 1,
      "transaction_id" : "2000000139167031",
      "is_in_trial_period" : false,
      "is_in_intro_offer_period"
2022-12-03 12:32:19.646588+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST receipts
2022-12-03 12:32:19.652439+0100 app[673:61340] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
2022-12-03 12:32:25.963962+0100 app[673:61358] [Purchases] - DEBUG: ℹ️ API request completed: POST /v1/receipts 200
2022-12-03 12:32:25.985723+0100 app[673:61358] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Finished
2022-12-03 12:32:25.985999+0100 app[673:61358] [Purchases] - DEBUG: ℹ️ Serial request done: POST receipts, 0 requests left in the queue
2022-12-03 12:32:25.989746+0100 app[673:61074] [Purchases] - INFO: 💰 Finishing transaction '2000000218313433' for product 'product2'

```
4. Steps to reproduce, with a description of expected vs. actual behavior: Try to purchase a product with an existing user that has already purchased and the subscription has expired.
5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Maybe the SDK can retry once the call if this error code is presented.

**Additional context**
Very similar to the question found in RC -> https://community.revenuecat.com/sdks-51/no-record-of-any-purchases-when-i-check-rc-website-recent-transactions-customers-etc-2008

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #2116.

Depends on #2134, #2144, #2145.

We've known that, especially for sandbox accounts with lots of purchases, the SDK can get flooded with a lot of transactions to process at once.
I've been making some improvements for this (like #2115).

Another consequence of this behavior, is that we can end up failing due to `StoreKit` throttling us (see #2116):

> 2022-12-03 12:31:58.670892+0100 app[673:61074] <SKReceiptRefreshRequest: 0x283edc860>: Finished refreshing receipt with error: Error Domain=ASDErrorDomain Code=603 "Request throttled" UserInfo={NSLocalizedFailureReason=Unified receipt is valid and current, NSLocalizedDescription=Request throttled, AMSServerErrorCode=0}

This change avoids that by skipping the refresh if less than 2 seconds have elapsed. I chose 2 to make this a low-ish risk change, with a huge benefit for multiple semi-concurrent requests coming from a big transaction queue.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Note that there are 4 PRs in this diff. The only change is [this commit](https://github.com/RevenueCat/purchases-ios/pull/2146/commits/de76eb9b9b9ca5a06274cb8c00fb346c49417c55).

File: Sources/Purchasing/ReceiptFetcher.swift [hunk 1]
```diff
@@ -19,26 +19,39 @@ class ReceiptFetcher {
...
+            if self.shouldThrottleRefreshRequest() {
+                Logger.debug(Strings.receipt.throttling_force_refreshing_receipt)
+
+                // If requested to refresh again within the throttle duration
+                // Use `ReceiptRefreshPolicy.onlyIfEmpty` so receipt is not refreshed if it's already loaded.
+                self.receiptData(refreshPolicy: .onlyIfEmpty, completion: completion)
+            } else {
+                Logger.debug(Strings.receipt.force_refreshing_receipt)
+                self.refreshReceipt(completion)
+            }
```
Comment (aboedo) [inline Sources/Purchasing/ReceiptFetcher.swift:54]: makes sense. I wonder if a more reliable way of doing this would be to throttle unless we've had a response for the last request, i.e.: there are no requests in flight. 

Do we know from the logs if for the customers that encountered this, they were throttled while a refresh was in flight or they were throttled after successful but frequent requests finished?

Comment (NachoSoto) [reply Sources/Purchasing/ReceiptFetcher.swift:54]: > makes sense. I wonder if a more reliable way of doing this would be to throttle unless we've had a response for the last request, i.e.: there are no requests in flight.

In most of these cases we're not doing concurrent requests, because we handle transactions linearly (see the example log in #2116). The problem is that we're refreshing it multiple times every second.

> Do we know from the logs if for the customers that encountered this, they were throttled while a refresh was in flight or they were throttled after successful but frequent requests finished?

See log:
```
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218313433 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218320027 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218327443 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218334901 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218342186 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218353996 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218362596 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218370255 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ PaymentQueue updatedTransaction: product2 2000000218377794 2000000042575785 1
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
<SKReceiptRefreshRequest: 0x283edc860>: Finished refreshing receipt with error: Error Domain=ASDErrorDomain Code=603 "Request throttled" UserInfo={NSLocalizedFailureReason=Unified receipt is valid and current, NSLocalizedDescription=Request throttled, AMSServerErrorCode=0}
DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/5E49D650-1DE9-40C7-A20C-147D6C8718F8/StoreKit/sandboxReceipt
```

All those happen within the same second.

Comment (aboedo) [reply Sources/Purchasing/ReceiptFetcher.swift:54]: that highlights what I mean, though - we don't wait until we get the response from SKReceiptRefreshRequest before allowing for the next request to start, right? the logs there show a single finish

Comment (NachoSoto) [reply Sources/Purchasing/ReceiptFetcher.swift:54]: Ooooh I see what you're saying.
Okay, I think maybe a better fix would be to reuse the completion block for concurrent receipt requests instead of throttling them.

That's what you have in mind too?

Comment (aboedo) [reply Sources/Purchasing/ReceiptFetcher.swift:54]: chatted about this offline - we already have a mechanism for this, it's just not enough if the receipt request finishes quickly.

**Review by aboedo — APPROVED** [review]

**Comment by NachoSoto** [comment]
This will help a lot prevent receipt refresh errors. Will merge once #2134 and #2145 are approved.
