### PR TITLE
`Xcode 15`: fix non-`visionOS` build by replacing `.custom` platform

### LINKED ISSUE #2998: RevenueCat fails to build with Xcode 15 Beta 6
I am unable to build RevenueCat 4.25.3 using Xcode 15 Beta 6.

When building for macOS I get the error "No such module 'UIKit'" in `UIApplication+RCExtensions.swift`, and when building for iOS I get the error "'purchase(confirmIn:options:)' is only available in iOS 17.0 or newer" in `PurchasesOrchestrator.swift`.  It seems like there is an issue with the changes made in https://github.com/RevenueCat/purchases-ios/pull/2989 and the VISION_OS flag is always being set.

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #2998. See #2989 for why this is needed in the first place.
This is now fixed in SPM: https://github.com/apple/swift-package-manager/pull/6794, but we need a workaround for now.

Since `.custom` doesn't work properly (it gets evaluated in Xcode even outside of that platform), this splits `Package.swift` based on Xcode version.

Thanks @neonichu for helping with this.

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -16,21 +16,14 @@ if shouldIncludeDocCPlugin {
...
-
 let package = Package(
     name: "RevenueCat",
     platforms: [
         .macOS(.v10_13),
         .watchOS("6.2"),
         .tvOS(.v11),
-        .iOS(.v11)
+        .iOS(.v11),
+        .visionOS(.v1)
```
Comment (NachoSoto) [inline Package.swift:26]: An advantage of this is being able to define this too, even though for some reason it's not actually required.

**Review by tonidero — APPROVED** [review]
Not very familiar with this, but makes sense 🚢

File: Package@swift-5.8.swift [hunk 2]
```diff
@@ -0,0 +1,56 @@
+// swift-tools-version:5.8
```
Comment (aboedo) [inline Package@swift-5.8.swift:1]: can this be 5.6 again?

Comment (NachoSoto) [reply Package@swift-5.8.swift:1]: Just added a separate `Package@swift-5.7.swift` to keep Xcode 14.1 compatibility (the min to submit to the App Store), and added a CI job to verify that.
