### PR TITLE
[EXTERNAL] Fix #5549: Use entitlement identifier as title for promotional entitlements (#6530) via @cruisediary

### LINKED ISSUE #5549: 🐛 Customer Center - Entitlement identifier now shows as one-time purchase
### Describe the bug

In a recent PR - https://github.com/RevenueCat/purchases-ios/pull/5465 it was changed how a entitlement is shown as purchase. 

| 5.35.1 | 5.38.2 |
|--------|--------|
| Image | Image | 

This is not what I expect to see. In our setup - we have a `grandfathered` entitlement - description `Early Adopters` with no attached products. We grant this entitlement for users without the use of a paywall and look for this entitlement to hide/show a paywall.

If I'm a user - I don't know what `One-Time Purchase` is. No where in the updated customer center does it tell me. 

Below is the "purchase" 
| Header | Header |
|--------|--------|
| Image | Image | 

### Platform

iOS

### SDK version

5.38.2

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

26.0

### Xcode version

16.5

### Device and/or simulator

Device

### Environment

Sandbox

### How widespread is the issue

100

### Debug logs

```shell
N/A
```

### Steps to reproduce

Have a RC entitlement without any attached products. Grant that entitlement to a user and view the customer center. Screenshots of what you see are above.

In the best case scenario - I would love to see the description (not the identifier) of the entitlement shown in the customer center. 

### Other information

```markdown

```

### Additional context

```markdown

```

### PR DESCRIPTION
**Pull request by vegaro**
Merging https://github.com/RevenueCat/purchases-ios/pull/6530 on main

I investigated using entitlement display name instead of identifier for promotional entitlements in Customer Center. The display name is stored in the DB but not included in the CustomerInfo API response so adding it would require a backend serializer change that impacts every CustomerInfo request, which isn't worth the cost for this use case in my opinion.

I've decided to keep the current PR approach of using the entitlemen identifier as the fallback title. If we want proper display names long-term, the right solution is a separate cacheable endpoint for entitlement metadata, but that's out of scope here.

---

> [!NOTE]
> **Low Risk**
> Low risk: small change to `PurchaseInformation` title fallback logic, only affecting promotional purchases when no StoreKit product title is available.
> 
> **Overview**
> Updates Customer Center purchase title resolution so that **promotional** purchases without a StoreKit product now display the entitlement `identifier` instead of the generic purchase-type label.
> 
> Refactors `determineTitle` to accept `entitlement` and `store`, and expands tests to cover promotional fallback behavior (including no-entitlement fallback and StoreKit-title precedence) while keeping non-promotional stores (e.g. Play Store) falling back to the subscription/one-time type label.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 32c28c4bdfc690f46cd4ef7d87ce60400d7764e1. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift [hunk 1]
```diff
@@ -537,14 +539,20 @@ extension PurchaseInformation {
...
         subscribedProduct: StoreProduct?,
+        store: Store,
         isSubscription: Bool,
         localization: CustomerCenterConfigData.Localization
     ) -> String {
         if let localizedTitle = subscribedProduct?.localizedTitle, !localizedTitle.isEmpty {
             return localizedTitle
         }
 
+        if store == .promotional, let identifier = entitlement?.identifier, !identifier.isEmpty {
```
Comment (tonidero) [inline RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift:552]: Just to confirm, we want to display the `entitlement.identifier`? Not sure if that's consumer facing in all cases? Just to make sure this doesn't make an unintended change in some apps.

**Review by tonidero — APPROVED** [review]
Just a question, but code looks good to me!

File: RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift (hunk 1 above)
Comment (vegaro) [reply RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift:552]: yes. I added a note to the PR description.

> I investigated using entitlement display name instead of identifier for promotional entitlements in Customer Center. The display name is stored in the DB but not included in the CustomerInfo API response so adding it would require a backend serializer change that impacts every CustomerInfo request, which isn't worth the cost for this use case in my opinion,<br><br>I've decided to keep the current PR approach of using the entitlemen identifier as the fallback title. If we want proper display names long-term, the right solution is a separate cacheable endpoint for entitlement metadata, but that's out of scope here.

Given the fact that two devs already reported this, I think it's better to show the identifier at least for now
