### PR TITLE
`PaymentQueueWrapper`: improved abstraction for active `SKPaymentQueue` wrapper

### LINKED ISSUE #1964: Unable to buy the same Product twice in the same app session
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

I'm unable to purchase the same consumable twice in the same app session. Due to our app having various items for purchase, we've set up 3 Products for purchase and the items for sale in our app are linked to one of the 3 Products, which sets the item's price. The issue we're having is that the SDK doesn't attempt to make a purchase if the same Product was bought in the current app session. We're calling .purchase(Product) and on the second purchase, we automatically get a successful callback and the transactions made for the previous Product is returned, instead of making a new purchase. Closing and reopening the app apparently clears the cache and the user is able to purchase the Product then, but again only the first one.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.13.1
   3. StoreKit 2 (_enabled with `useStoreKit2IfEnabled`_) (Y/N): Y
   4. OS version: 16.0.2
   5. Xcode version: 14.0.1
   6. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

I'm using the sandbox environment

### PR DESCRIPTION
**Pull request by NachoSoto**
This is a follow up to #1901 and #1882. Depends on #1967.
Essentially before this change, `Purchases` had both `StoreKit1Wrapper?` and a `PaymentQueueWrapper`. The later wasn't actually needed when the first was not-nil, so it was essentially storing `(a?, b?)`. What we really wanted to express is that it could have one OR the other.

This introduces `Either` to express this requirement in the type system, as well as `PaymentQueueWrapperType` that will be used to fix #1964.

### CODE REVIEW

File: Sources/Purchasing/Purchases/Purchases.swift [hunk 1]
```diff
@@ -455,16 +451,14 @@ public typealias StartPurchaseBlock = (@escaping PurchaseCompletedBlock) -> Void
...
         } else {
             Logger.warn(Strings.configure.autoSyncPurchasesDisabled)
         }
 
         /// If SK1 is not enabled, `PaymentQueueWrapper` needs to handle transactions
         /// for promotional offers to work.
-        if !self.isStoreKit1Configured {
-            self.paymentQueueWrapper.delegate = purchasesOrchestrator
-        }
+        self.paymentQueueWrapper.right?.delegate = purchasesOrchestrator
```
Comment (tonidero) [inline Sources/Purchasing/Purchases/Purchases.swift:461]: Hmm I wonder if we could add another extension to `EitherPaymentQueueWrapper` to access the `PaymentQueueWrapper`. Something like `.paymentQueueWrapper` instead of `.right` to make clearer what it is. So this would become: `self.paymentQueueWrapper.paymentQueueWrapper?.delegate = purchasesOrchestrator`

File: Sources/Purchasing/Purchases/Purchases.swift [hunk 2]
```diff
@@ -479,8 +473,8 @@ public typealias StartPurchaseBlock = (@escaping PurchaseCompletedBlock) -> Void
 
     deinit {
         self.notificationCenter.removeObserver(self)
-        self.storeKit1Wrapper?.delegate = nil
-        self.paymentQueueWrapper.delegate = nil
+        self.paymentQueueWrapper.left?.delegate = nil
+        self.paymentQueueWrapper.right?.delegate = nil
```
Comment (tonidero) [inline Sources/Purchasing/Purchases/Purchases.swift:477]: These could potentially use the `storeKit1Wrapper` (and `paymentQueueWrapper` if we add it) extension functions instead of `left` and `right`.

**Review by tonidero — APPROVED** [review]
Looks good, just a comment about a possible change but NABD.

File: Sources/Purchasing/Purchases/Purchases.swift (hunk 1 above)
Comment (NachoSoto) [reply Sources/Purchasing/Purchases/Purchases.swift:461]: Yeah that's a good suggestion, let me do that.

File: Sources/Purchasing/Purchases/Purchases.swift (hunk 2 above)
Comment (NachoSoto) [reply Sources/Purchasing/Purchases/Purchases.swift:477]: Changed
