### PR TITLE
Fixed `PurchasesOrchestrator` compilation error on Xcode 14.3 beta 1

### LINKED ISSUE #2291: Xcode 14.3 support
image

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #2291.

This has led to issues in the past too (#1994, #2221, 	https://github.com/RevenueCat/purchases-flutter/issues/516, https://github.com/RevenueCat/purchases-flutter/issues/507) because I tried to reuse that code to call a single completion method.
The new version of Swift makes that impossible now, because it detects that `@MainActor` isn't available in iOS 12.

To finally work around all those issues, this simply duplicates this single line of code, which should work across all versions of Swift.

### CODE REVIEW

File: Sources/Purchasing/Purchases/PurchasesOrchestrator.swift [hunk 1]
```diff
@@ -957,23 +957,12 @@ private extension PurchasesOrchestrator {
...
-                #endif
-
                 if finishable {
-                    self.finishTransactionIfNeeded(transaction) { complete() }
+                    self.finishTransactionIfNeeded(transaction) {
+                        completion?(transaction, nil, purchasesError, false)
+                    }
                 } else {
-                    complete()
+                    completion?(transaction, nil, purchasesError, false)
```
Comment (aboedo) [inline Sources/Purchasing/Purchases/PurchasesOrchestrator.swift:965]: honestly this is easier to read too

**Review by aboedo — APPROVED** [review]

**Review by tonidero — APPROVED** [review]

File: Sources/Purchasing/Purchases/PurchasesOrchestrator.swift (hunk 1 above)
Comment (NachoSoto) [reply Sources/Purchasing/Purchases/PurchasesOrchestrator.swift:965]: Yeah totally 🤷🏻‍♂️ not sure why I didn't realize it earlier that we could go back to this.
