### PR TITLE
Fix `FileHandler`'s potential crash on writing

### LINKED ISSUE #5667: 🐛 FileHandler actor's append(line:) method crashes on some devices
### Describe the bug

I am getting rare crashes from some users. The problem starts with `PaywallEventsManager.track(featureEvent:)` which seems to call `PaywallEventStore.store(_:)` and that calls `FileHandler.append(line:)`. Perhaps due to insufficient space or some other problem, this method crashes at line 81 on `self.fileHandle.write(line.asData)`

The issue can happen both in background or while the app is open. I see crashes from iOS 15 and 18, so perhaps it affects all iOS versions.

### Platform

iOS

### SDK version

RevenueCat 5.44.0

### SDK integration method

Swift Package Manager

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 15-18

### Xcode version

26.0

### Device and/or simulator

Device

### Environment

Production

### How widespread is the issue

Rare, perhaps 1%

### Debug logs

```shell
Last Exception Backtrace:
0   CoreFoundation                	0x18f2880c0 __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x18c721abc objc_exception_throw + 88 (objc-exception.mm:356)
2   Foundation                    	0x18e07054c _NSFileHandleRaiseOperationExceptionWhileReading + 272 (NSFileHandle.m:72)
3   Foundation                    	0x18de6a8ac -[NSConcreteFileHandle writeData:] + 300 (NSFileHandle.m:905)
4   MyApp                       	0x101233f28 FileHandler.append(line:) + 20 (FileHandler.swift:81)
5   MyApp                       	0x101233f28 protocol witness for FileHandlerType.append(line:) in conformance FileHandler + 20 (/<compiler-generated>:77)
6   MyApp                       	0x101233f28 PaywallEventStore.store(_:) + 144 (PaywallEventStore.swift:50)
7   MyApp                       	0x1012b23ad specialized PaywallEventsManager.track(featureEvent:) + 1 (PaywallEventsManager.swift:50)
8   MyApp                       	0x1012a12a1 <deduplicated_symbol> + 1
9   MyApp                       	0x100dce341 <deduplicated_symbol> + 1
10  MyApp                       	0x100eff831 <deduplicated_symbol> + 1
11  MyApp                       	0x100dce6bd <deduplicated_symbol> + 1
12  MyApp                       	0x100e3c591 specialized thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A) + 1
13  MyApp                       	0x100dce6bd <deduplicated_symbol> + 1
14  libswift_Concurrency.dylib    	0x19abd1241 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1 (Task.cpp:537)
```

### Steps to reproduce

I myself cannot reproduce the problem.

### Other information

```markdown

```

### Additional context

```markdown

```

### PR DESCRIPTION
**Pull request by ajpallares**
Fixes #5667

### Motivation
The `FileHandler` `append(line:)` method was using an older API that would produce a crash when writing to the file fails (e.g. not enough disk space available) instead of throwing an error. See https://developer.apple.com/documentation/foundation/filehandle/write(_:).

### Description
This PR changes it to use the newer [`FileHandle`'s `write(contentsOf:)` API](https://developer.apple.com/documentation/foundation/filehandle/write(contentsof:))

### CODE REVIEW

**Review by rickvdl — APPROVED** [review]

File: Sources/Diagnostics/FileHandler.swift [hunk 1]
```diff
@@ -21,7 +21,8 @@ protocol FileHandlerType: Sendable {
     func readLines() async throws -> AsyncLineSequence<FileHandle.AsyncBytes>
 
     /// Adds a line at the end of the file
-    func append(line: String) async
+    @available(macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4, *)
```
Comment (tonidero) [inline Sources/Diagnostics/FileHandler.swift]: Very nitpicky, but I like to put iOS first, since it's the main platform. No preference for the others.

File: Sources/Diagnostics/FileHandler.swift [hunk 2]
```diff
@@ -74,12 +75,13 @@ actor FileHandler: FileHandlerType {
     }
 
     /// Adds a line at the end of the file
-    func append(line: String) {
+    @available(macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4, *)
+    func append(line: String) throws {
         RCTestAssertNotMainThread()
 
         self.fileHandle.seekToEndOfFile()
```
Comment (JayShortway) [inline Sources/Diagnostics/FileHandler.swift]: There's also `seekToEnd()`, which is maybe newer? I genuinely don't know haha.

```suggestion
        self.fileHandle.seekToEnd()
```

**Review by JayShortway — APPROVED** [review]
Beautiful! 😗👌 Just a suggestion/question.

File: Sources/Diagnostics/FileHandler.swift (hunk 1 above)
Comment (ajpallares) [reply Sources/Diagnostics/FileHandler.swift]: Overside from my part. Totally my kind of nitpicks. Thank you! Done in https://github.com/RevenueCat/purchases-ios/pull/5675/commits/37c511d9268609923ae70ce4c03129671584e698

File: Sources/Diagnostics/FileHandler.swift (hunk 2 above)
Comment (ajpallares) [reply Sources/Diagnostics/FileHandler.swift]: Oh, great catch! Thank you! Done in f16e0b96fd51f9f08105f7be941e726f428f0bce
