### PR TITLE
Fix icon not updating on selection of package

### LINKED ISSUE #5844: 🐛 SDK 5.47.1 and later cannot change icons after a package is selected or unselected
### Describe the bug

SDK 5.47.1 and later cannot change icons after a paywall is loaded. See the screenshots.

The first screenshot is from 5.47.0. In the paywall, the monthly package comes selected as default and I select the yearly package by hand. You can see that in the first screenshot, the icon changed to a circle with checkmark for the yearly package and it is reverted to an empty circle for the monthly package.

Image

Now check the second screenshot from 5.48.0 (5.47.1 is also the same). The icon did not change to the circle with checkmark for the yearly package and it is still circle with checkmark for the monthly package even though it is not selected.

Image

### Platform

iOS

### SDK version

5.47.1 and later

### SDK integration method

Swift Package Manager

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 26.0

### Xcode version

26.1

### Device and/or simulator

Device

### Environment

Production

### How widespread is the issue

100%

### Debug logs

```shell
Will provide if needed.
```

### Steps to reproduce

Simply open the paywall and tap packages that include icons

### Other information

```markdown

```

### Additional context

```markdown

```

### PR DESCRIPTION
**Pull request by JZDesign**
### Checklist
- [ ] If applicable, unit tests
- [ ] If applicable, create follow-up issues for `purchases-android` and hybrids

### Motivation

resolves #5844 

We have an issue updating the icon after package selection.

### Description

It broke in 5.47.1 for some people, It has to do with the changes in #5775, but I cannot reproduce it. My best hunch is that the StateObjects that are inside of the RemoteImageView are surviving the URL update because the identity of the view did not change. This would cause the retention of the URL and the bug that we see.

>[!NOTE]
> Joan and one of the bug reporters both tested and confirmed this resolves the bug

|Before|After|
|:----:|:----:|
|before|After|

### CODE REVIEW

File: RevenueCatUI/Templates/V2/Components/Icon/IconComponentViewModel.swift [hunk 1]
```diff
@@ -45,7 +45,7 @@ class IconComponentViewModel {
         let fixedHeight: CGFloat?
 
         // Get fixed width (if exists)
-        switch self.component.size.height {
+        switch self.component.size.width {
```
Comment (JZDesign) [inline RevenueCatUI/Templates/V2/Components/Icon/IconComponentViewModel.swift:48]: Unrelated bug that I figured I'd fix while I was in here.

File: RevenueCatUI/Views/RemoteImage.swift [hunk 2]
```diff
@@ -113,10 +113,10 @@ private struct ColorSchemeRemoteImage<Content: View>: View {
 
     // Preferred method of loading images
 
-    @StateObject
+    @ObservedObject
     private var highResFileLoader: FileImageLoader
 
-    @StateObject
+    @ObservedObject
```
Comment (JZDesign) [inline RevenueCatUI/Views/RemoteImage.swift:119]: The FileImageLoader is initialized with a URL. StateObjects are only instantiated on the identity change of a view, if the redraw did not trigger an identity change, then the URL never updates and we see the same image from before.

Comment (facumenzella) [reply RevenueCatUI/Views/RemoteImage.swift:119]: I think this is not correct. If we mark these as `ObservedObject` then a parent should have them as `StateObject`, right?

I wonder if adding a `.id(url)` to `ColorSchemeRemoteImage` could address this

Comment (JZDesign) [reply RevenueCatUI/Views/RemoteImage.swift:119]: There is no need to retain the state here. The result of the load doesn't cause parent view redraws or any reason for us to need to retain the state.

Adding .id certainly would address the issue if done in the IconComponentView and the ImageComponentView. But you'll notice that it will cause the same reinitialization of the `FileImageLoaders` so the difference is only that this implementation has to create 2 less StateObject wrappers

Comment (JZDesign) [reply RevenueCatUI/Views/RemoteImage.swift:119]: TLDR: There is no requirement or need for a parent to retain them as state objects and that would result in the same bug.

**Review by facumenzella — APPROVED** [review]
