### PR TITLE
[EXTERNAL] fix: listen willResignActiveNotification and didBecomeActiveNotification to autoplay the video

### LINKED ISSUE #6007: 🐛 iOS video playback stops playing when app is backgrounded, doesnt autoplay when app is foregrounded
### Describe the bug

If a paywall with background video opens and you lock the device/move app to background and unlock device/open app, the paywall background video doesnt seem to be autoplaying. It just stops a certain timestamp.

### Platform

iOS

### SDK version

5.53.0

### SDK integration method

CocoaPods

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 26.1

### Xcode version

16.4

### Device and/or simulator

Device

### Environment

Production

### How widespread is the issue

100%

### Debug logs

```shell
No logs needed.
```

### Steps to reproduce

1. Create a paywall that has background video
2. Navigate to Revenuecat's official app or your own app for preview
3. View the paywall
4. Lock your device/move app to background
5. Unlock your device/move app to foreground
6. See that video is not playing

### Other information

```markdown

```

### Additional context

```markdown
I have discovered this issue while using react-native-purchases and react-native-purchases-ui sdk's, both of them in latest `9.6.13` version. Issue also seems to be affecting RevenueCat's iOS app.
```

### PR DESCRIPTION
**Pull request by erenkulaksiz**
### Checklist
- [ ] If applicable, unit tests
- [ ] If applicable, create follow-up issues for `purchases-android` and hybrids

### Motivation

Resolves #6007 

### Description

On VideoPlayerViewUIView:

Added a Coordinator so it listens to both `willResignActiveNotification` and `didBecomeActiveNotification`.

- `appWillResignActive` used for getting current video player status (is playing or not)
- `didBecomeActiveNotification` checks latest status and plays the video if it was playing before.

Old pr: #6009

### CODE REVIEW

File: RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift [hunk 1]
```diff
@@ -75,5 +75,47 @@ struct VideoPlayerUIView: UIViewControllerRepresentable {
...
+
+        @objc private func appDidBecomeActive() {
+            if wasPlayingBeforeBackground {
+                player.play()
+            }
+        }
+
+        deinit {
+            NotificationCenter.default.removeObserver(self)
+        }
```
Comment (facumenzella) [inline RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: Instead of doing this here, I think we can use https://developer.apple.com/documentation/swiftui/uiviewcontrollerrepresentable/dismantleuiviewcontroller(_:coordinator:)-30a1m right? 🤔

Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: OR go with the combine approach, and do something like:

```
          notificationCenter.publisher(for: UIApplication.willResignActiveNotification)                                             
              .sink { [weak self] _ in self?.appWillResignActive() }                                                                
              .store(in: &cancellables)                                                                                             
                                                                                                                                    
          notificationCenter.publisher(for: UIApplication.didBecomeActiveNotification)                                              
              .sink { [weak self] _ in self?.appDidBecomeActive() }                                                                 
              .store(in: &cancellables)   
```

this should auto-cleanup too

Comment (erenkulaksiz) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: Hello @facumenzella , do you mean something like this:
```swift
class Coordinator {
    let player: AVPlayer
    private var wasPlayingBeforeBackground: Bool = false
    private var cancellables = Set<AnyCancellable>()

    init(player: AVPlayer) {
        self.player = player

        NotificationCenter.default.publisher(for: UIApplication.willResignActiveNotification)
            .sink { [weak self] _ in self?.appWillResignActive() }
            .store(in: &cancellables)

        NotificationCenter.default.publisher(for: UIApplication.didBecomeActiveNotification)
            .sink { [weak self] _ in self?.appDidBecomeActive() }
            .store(in: &cancellables)
    }

    private func appWillResignActive() {
        wasPlayingBeforeBackground = player.timeControlStatus == .playing
    }

    private func appDidBecomeActive() {
        if wasPlayingBeforeBackground {
            player.play()
        }
    }
}
```

Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: Yeah I was thinking something about that, in case the `Coordinator` is retained for some reason

**Comment by facumenzella** [comment]
Hey! This looks good, but heads up - there's a merge conflict now. `main` already has a `Coordinator` class that handles restoring the `AVAudioSession` category when the view is dismissed.

Could you rebase and merge your background/foreground logic into that existing Coordinator? Should be pretty straightforward - just add your `wasPlayingBeforeBackground`, `cancellables`, and the notification subscriptions to the existing class.

**Comment by erenkulaksiz** [comment]
> Hey! This looks good, but heads up - there's a merge conflict now. `main` already has a `Coordinator` class that handles restoring the `AVAudioSession` category when the view is dismissed.
> 
> Could you rebase and merge your background/foreground logic into that existing Coordinator? Should be pretty straightforward - just add your `wasPlayingBeforeBackground`, `cancellables`, and the notification subscriptions to the existing class.

Hello, sorry for the late response. I will do that tomorrow. Thanks!

**Review by facumenzella — APPROVED** [review]
