### PR TITLE
`Paywalls`: loading indicator for in-progress purchases

### LINKED ISSUE #3216: [ RevenueCatUI ] - Custom Loading View for PaywallView and PaywallFooter
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**The solution**
Create an *extension view* similar to `onPurchaseCompleted/onRestoreCompleted´ that returns Bool to control the display of a Custom Loading View.

I have a custom loading throughout my application, but in RevenueCatUI I lose this UI consistency, because I did not find an "uncomplicated" way to do this simple action and receive the status of actionInBlock.
In my specific case I have an extension for the View called `.loading´ that receives a bool parameter with this implementation I could easily add my custom loading.

Por ex: 

```swift
  @State
  private var displayPaywall: Bool = true

  @State
  private var isLoading: Bool = true

  var body: some View {
     ContentView()
         .sheet(isPresented: self.$displayPaywall) {
             PaywallView()
                 .onLoadingStatus { status in
                     self.isLoading = status
                }
                .loading(self.isLoading)
         }
  }
```

A positive point for this approach also works for `paywallFooter´ and taking complexity and adding customization to each project.

Already taking the opportunity to say that a `onUserCancel´ is also positive so that you can have the opportunity to track the event and also display an offer to the user, an opportunity in view of the fact that many checkouts are started and canceled.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.26.0-beta.4
   3. StoreKit version:
      - [x] StoreKit 1
      - [ ] StoreKit 2 (_enabled with `usesStoreKit2IfAvailable(true)`_)
   4. OS version: 16
   5. Xcode version: 14
   6. Device and/or simulator:
      - [x] Device
      - [x] Simulator
   7. Environment:
      - [x] Sandbox
      - [x] TestFight
      - [x] Production
   8. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue. **Complete logs with `Purchases.logLevel = .verbose` will help us debug this issue.**

3. Steps to reproduce, with a description of expected vs. actual behavior
Not necessary.

4. Another context that creates an inconsistency is when the paywall is displayed via shet where the user can close even after clicking buy due to the delay of the apple popup. 
It can be corrected with the developer obtaining the status and blocking the closure of the shet

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #3216.

This likely got broken with #3121 because we stopped using `.buttonStyle`. This implements a manual style when the button is `disabled` (when `PurchaseHandler.actionInProgress` is `true`).

https://github.com/RevenueCat/purchases-ios/assets/685609/0e23bcf1-7e1d-4d57-adf7-61a76b1e997e

### CODE REVIEW

File: RevenueCatUI/Views/PurchaseButton.swift [hunk 1]
```diff
@@ -59,39 +59,29 @@ struct PurchaseButton: View {
...
-    var userInterfaceIdiom
-
     var body: some View {
         self.button
     }
 
     private var button: some View {
         AsyncButton {
             guard !self.purchaseHandler.actionInProgress else { return }
+            guard !self.package.currentlySubscribed else { return }
```
Comment (NachoSoto) [inline RevenueCatUI/Views/PurchaseButton.swift:69]: Doing this instead of marking the button as `disabled`, which would display a spinner now.

File: RevenueCatUI/Views/PurchaseButton.swift [hunk 2]
```diff
@@ -116,6 +106,46 @@ struct PurchaseButton: View {
...
+            foregroundColor: self.colors.callToActionForegroundColor
+        )
+            .frame(
+                maxWidth: self.mode.fullWidthButton
+                   ? .infinity
+                    : nil
+            )
+            .padding()
+            .padding(.vertical, self.userInterfaceIdiom == .pad ? 10 : 0)
+            .hidden(if: !self.isEnabled)
```
Comment (NachoSoto) [inline RevenueCatUI/Views/PurchaseButton.swift:137]: Always displaying this to keep layout consistent, but hiding it when the button is disabled.

File: RevenueCatUI/Views/PurchaseButton.swift [hunk 3]
```diff
@@ -116,6 +106,46 @@ struct PurchaseButton: View {
...
+            .overlay {
+                if !self.isEnabled {
+                    ProgressView()
```
Comment (aboedo) [inline RevenueCatUI/Views/PurchaseButton.swift:140]: Super minor, FFTI: but given that it goes into a loading state when it's not enabled, maybe the flag should be something like `isLoading` or `hasOperationInProgress` or something to reflect that

**Review by aboedo — APPROVED** [review]

**Review by joshdholtz — APPROVED** [review]

File: RevenueCatUI/Views/PurchaseButton.swift (hunk 3 above)
Comment (NachoSoto) [reply RevenueCatUI/Views/PurchaseButton.swift:140]: But it's coming from the `.isEnabled` environment variable, that's why I named it as such 🤔
