### PR TITLE
[EXTERNAL] fix: dont show video in now playing (control center/lock screen #6115 via @erenkulaksiz

### LINKED ISSUE #6006: 🐛 iOS video playback, shows the video controls in "Now Playing" (lock screen/control center)
### Describe the bug

While viewing a paywall with a background video, lock your device or open the control center, you can see the paywall video's controls like play pause etc. Paywall video controls should not appear on control center and lock screen.

### Platform

iOS

### SDK version

5.53.0

### SDK integration method

CocoaPods

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 26.1

### Xcode version

16.4

### Device and/or simulator

Device

### Environment

TestFlight

### How widespread is the issue

100%

### Debug logs

```shell
No logs needed.
```

### Steps to reproduce

1. Create a paywall that has background video
2. Navigate to Revenuecat's official app or your own app for preview
3. View the paywall
4. Lock your device / open control center
5. See your app's name with video controls (play/pause)

### Other information

```markdown

```

### Additional context

```markdown
I have discovered this issue while using react-native-purchases and react-native-purchases-ui sdk's, both of them in latest `9.6.13` version. Issue also seems to be affecting RevenueCat's iOS app.
```

### PR DESCRIPTION
**Pull request by facumenzella**
### Motivation
Resolves #6006 via @erenkulaksiz

### Description

I have observed that media also could be viewed in Dynamic Island.

Set `preventsDisplaySleepDuringVideoPlayback`, `allowsExternalPlayback` to false, to make sure the media doesnt show up in now playing.

Used ambient category for AVAudioSession, making it so that it doesnt block other audio while video is playing. 

On AVPlayerViewController, set `allowsPictureInPicturePlayback` to false, to make sure this media cant be played elsewhere.

Old pr: #6009

### CODE REVIEW

File: RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift [hunk 1]
```diff
@@ -58,11 +61,31 @@ struct VideoPlayerUIView: UIViewControllerRepresentable {
         }
     }
 
+    func makeCoordinator() -> Coordinator {
+        Coordinator()
+    }
+
     func makeUIViewController(context: Context) -> AVPlayerViewController {
+        let audioSession = AVAudioSession.sharedInstance()
+        context.coordinator.previousCategory = audioSession.category
```
Comment (rickvdl) [inline RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift:72]: Please correct me if I'm wrong, but this is in order to restore the original settings of the app before the paywall was displayed right? In that case I'm not sure if this is 100% reliable (I'm thinking of presenting a second paywall through exit offers for example). I'm not sure if I have a better idea, and it might actually work fine. Just thinking about some edge cases here :)

Comment (erenkulaksiz) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift:72]: Hello, yes this is for exactly that. Opening an exit offer (2nd paywall) probably going to use the previous category from the first paywall, and it should return back to original state when both paywalls are closed.

Can you by any chance test this previous category section with an exit offer? because I dont have the enough resources to test currently. If we find any issues, we can think about another solution.

Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift:72]: I thought about this last week. When using exit offers, the first paywall is closed before the second one is presented, so the flow is:                                                                                                                          
                                                                                                                                    
  1. First paywall opens → stores original audio category, sets .ambient                                                            
  2. First paywall closes → deinit restores original audio category                                                                 
  3. Exit offer opens → stores original audio category (correctly restored), sets .ambient                                          
  4. Exit offer closes → deinit restores original audio category                                                                    

Since the paywalls are sequential rather than nested, each Coordinator independently captures and restores the correct state. It should work correctly for most cases (as you say, not 100% reliable).

Comment (rickvdl) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift:72]: Thanks for the context @erenkulaksiz / @facumenzella! In that case it should work for this situation indeed, and it's probably the best we can come up with without adding too much complexity.

**Comment by facumenzella** [comment]
@RCGitBot please test

**Comment by facumenzella** [comment]
@RCGitBot please test

**Comment by facumenzella** [comment]
@RCGitBot please test
