### PR TITLE
Check for productsWithIntroOffers first, before backend

### LINKED ISSUE #982: checkTrialOrIntroductoryPriceEligibility returns "RCIntroEligibilityStatusEligible" when there are no intro offers
- [ -] I have updated Purchases SDK to the latest version
- [- ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [- ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ -] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ -] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Every time I call the "checkTrialOrIntroductoryPriceEligibility" API I get a status of "RCIntroEligibilityStatusEligible" but I don't have any introductory offers or promotional offers in App Store connect. I used to but I deleted them. 

1. Environment
   1. Platform: iOS
   2. SDK version: 3.13.0
   3. OS version: 15.1.1
   4. Xcode version: 13.1
   5. How widespread is the issue. Percentage of devices affected. All
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
[Debug_logs.txt](https://github.com/RevenueCat/purchases-ios/files/7576321/Debug_logs.txt)

3. Steps to reproduce, with a description of expected vs. actual behavior
In IntroEligibilityCalculator.swift line 42,
            let receipt = try receiptParser.parse(from: receiptData)
I po JSONSerialization.jsonObject(with: receiptData, options: .allowFragments)

and get this error
Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end around line 1, column 1." UserInfo={NSDebugDescription=Garbage at end around line 1, column 1., NSJSONSerializationErrorIndex=1}
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

### PR DESCRIPTION
**Pull request by taquitos**
If we can return productsWithIntroOffers for all productIds without asking the backend, we should. Otherwise, we should filter out the ids that we know about and only ask the backend for ones we don't.
Fixes #982

### CODE REVIEW

File: Purchases/Networking/Backend.swift [hunk 1]
```diff
@@ -372,10 +372,10 @@ class Backend {
         }
     }
 
-    func getIntroEligibility(appUserID: String,
-                             receiptData: Data,
-                             productIdentifiers: [String],
-                             completion: @escaping IntroEligibilityResponseHandler) {
+    func fetchIntroEligibility(appUserID: String,
```
Comment (NachoSoto) [inline Purchases/Networking/Backend.swift:375]: 👍  I like `fetch` much more for these.

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift [hunk 2]
```diff
@@ -141,4 +153,25 @@ fileprivate extension TrialOrIntroPriceEligibilityChecker {
         }
     }
 
+    @available(iOS 11.2, macOS 10.13.2, macCatalyst 13.0, tvOS 11.2, watchOS 6.2, *)
+    func productsWithIntroOffers(productIdentifiers: [String]) -> [String: IntroEligibility] {
+        var productIdsToIntroEligibleStatus: [String: IntroEligibility] = [:]
+        let group = DispatchGroup()
```
Comment (NachoSoto) [inline Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:159]: Seems weird to make this blocking.
Considering that the public method `Purchases.checkTrialOrIntroductoryPriceEligibility` is already "async" (completion block), maybe use the same pattern here?

Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:159]: I was thinking the same. My initial thought was it makes the logic easier if we return a value instead of completion, but you're right.

Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift]: Done ✅

**Review by NachoSoto — APPROVED** [review]

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift [hunk 3]
```diff
@@ -121,12 +121,59 @@ fileprivate extension TrialOrIntroPriceEligibilityChecker {
...
+    func getIntroEligibility(with receiptData: Data,
+                             productIdentifiers: [String],
+                             productIdsToIntroEligibleStatusFromApple: [String: IntroEligibility],
+                             completion: @escaping ReceiveIntroEligibilityBlock) {
+        // Remove any productIds we already have intro pricing for so we don't try to fetch them from the backend.
+        let idsToFetchFromBackend = productIdentifiers.filter { productIdsToIntroEligibleStatusFromApple[$0] == nil }
+        if idsToFetchFromBackend.isEmpty {
+            completion(productIdsToIntroEligibleStatusFromApple)
+            return
+        }
```
Comment (aboedo) [inline Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:172]: would this be simplified if this method only received `productIdentifiers` for products that have `introductoryPrice != nil`?

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift [hunk 4]
```diff
@@ -121,12 +121,59 @@ fileprivate extension TrialOrIntroPriceEligibilityChecker {
...
+
+        self.backend.fetchIntroEligibility(appUserID: self.appUserID,
+                                           receiptData: receiptData,
+                                           productIdentifiers: productIdentifiers) { backendResult, maybeError in
```
Comment (aboedo) [inline Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:176]: if `productIdentifiers` contains items that have `introductoryPrice == nil`, we're still sending them to the backend here, right? 
Ideally we only send the ones that have intro price to the backend to save on compute time

Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:176]: Just to be sure I'm on the same page:

Assume we have `productIdentifiers` which is a list of 4 ids:
`productIdentifiers = [A has introductoryPrice, B does not, C does not, D has introductoryPrice]`
1.  We fetch on device and notice `A` and `D` have `introductoryPrice`
2. `productIdsToIntroEligibleStatusFromApple` now contains `["A" : A, "D": D]`
3.  We pass `productIdentifiers` and `productIdsToIntroEligibleStatusFromApple` to `getIntroEligibility`
4. We remove any products that have `introductoryPrice` from `productIdentifiers` in line 168, so now we have:
`idsToFetchFromBackend == [B, C]` and
`productIdsToIntroEligibleStatusFromApple` == ["A" : A, "D": D]`
We pass `[B, C]` to the backend to check on.

Looks like I forgot to use `idsToFetchFromBackend` for the call to `self.backend.fetchIntroEligibility`

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 3 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:173]: Yes, I could do the filter before this method but it made the most sense to me to do the filtering here, instead. That way any callers to this func don't have to be concerned with their own filtering.

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift [hunk 5]
```diff
@@ -92,6 +93,23 @@ class TrialOrIntroPriceEligibilityChecker {
         return introDict
     }
 
+    @available(iOS 11.2, macOS 10.13.2, macCatalyst 13.0, tvOS 11.2, watchOS 6.2, *)
+    func productsWithIntroOffers(productIdentifiers: [String], completion: @escaping ReceiveIntroEligibilityBlock) {
```
Comment (aboedo) [inline Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:97]: this method could be `private`, right?

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift [hunk 6]
```diff
@@ -92,6 +93,23 @@ class TrialOrIntroPriceEligibilityChecker {
...
+            let eligibility: [(String, IntroEligibility)] = Array(products).compactMap {
+                guard $0.introductoryPrice != nil else {
+                    return nil
+                }
+                return ($0.productIdentifier, IntroEligibility(eligibilityStatus: .eligible))
+            }
+            var productIdsToIntroEligibleStatus: [String: IntroEligibility] = [:]
+            eligibility.forEach { (productId, eligibility) in
+                productIdsToIntroEligibleStatus[productId] = eligibility
+            }
```
Comment (aboedo) [inline Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:108]: I think this could be simplified using [this init](https://developer.apple.com/documentation/swift/dictionary/3127165-init)
```swift
let productIdsToIntroEligibleStatus = Dictionary(uniqueKeysWithValues: eligibility)
```

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift [hunk 7]
```diff
@@ -92,6 +93,23 @@ class TrialOrIntroPriceEligibilityChecker {
...
     }
 
+    @available(iOS 11.2, macOS 10.13.2, macCatalyst 13.0, tvOS 11.2, watchOS 6.2, *)
+    func productsWithIntroOffers(productIdentifiers: [String], completion: @escaping ReceiveIntroEligibilityBlock) {
+        self.productsManager.products(withIdentifiers: Set(productIdentifiers)) { products in
+            let eligibility: [(String, IntroEligibility)] = Array(products).compactMap {
+                guard $0.introductoryPrice != nil else {
+                    return nil
+                }
+                return ($0.productIdentifier, IntroEligibility(eligibilityStatus: .eligible))
```
Comment (aboedo) [inline Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:103]: FFTI: I had a bit of trouble understanding this block at first. Would this be easier to understand at a glance? 

```swift
let eligibility: [(String, IntroEligibility)] =
    Array(products)
    .filter { $0.introductoryPrice != nil }
    .map { ($0.productIdentifier, IntroEligibility(eligibilityStatus: .eligible)) }

let productIdsToIntroEligibleStatus = Dictionary(uniqueKeysWithValues: eligibility)
```

**Review by aboedo — APPROVED** [review]
looks great! left a couple of minor readability suggestions

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 5 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:97]: I had it private, originally, but then I wanted to mock it and so I switched it back. I ended up not mocking it and forgetting to move it back to the private extension 🤦‍♂️

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 6 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:108]: I totally forgot this was a thing!

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 7 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift:103]: So, I like what I wrote because, technically, we are compacting. I also agree with you, your solution is more readable. I think that's more important here 😄.

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 5 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift]: ✅

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 6 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift]: ✅

File: Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift (hunk 7 above)
Comment (taquitos) [reply Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift]: Updated ✅
