### PR TITLE
`PurchaseOrchestrator`: always refresh receipt purchasing in sandbox

### LINKED ISSUE #2260: 4.17.4 Break purchases
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: iOS
   2. SDK version: 4.17.4 
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N):
   4. OS version: 16.x
   5. Xcode version: 14.2.0
   6. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

Hi:

We notice through our UITests a purchase flow break, changing the version from 4.17.3 to 4.17.4.

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #2260 and [SDKONCALL-216].
Follow up to #2245.

The change in #2245 was meant to avoid receipt refresh throttling errors (#2116).
However, that was a regression when using StoreKit config files because those don't get refreshed in the backend.

Unfortunately the workaround introduced in #1945 prevented us from noticing this, because we use `DangerousSettings.InternalSettings.enableReceiptFetchRetry` in our own integration tests.
I added an integration test that explicitly covers this scenario. That fails without this change if disabling that dangerous setting. I thought about making that test run without the setting, but that might lead to flaky failures in CI, which is why we introduced that workaround in the first place. But at least now we have an explicit integration test for this, as well as 2 unit tests.

[SDKONCALL-216]: https://revenuecats.atlassian.net/browse/SDKONCALL-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: Sources/Purchasing/Purchases/PurchasesOrchestrator.swift [hunk 1]
```diff
@@ -781,7 +781,21 @@ private extension PurchasesOrchestrator {
                                              maximumRetries: Self.receiptRetryCount,
                                              sleepDuration: Self.receiptRetrySleepDuration)
         } else {
+            // See https://github.com/RevenueCat/purchases-ios/pull/2245 and
+            // https://github.com/RevenueCat/purchases-ios/issues/2260
+            // - Release or production builds:
+            //      We don't _want_ to always refresh receipts to avoid throttling errors
+            //      We don't _need_ to because the receipt will be refreshed by the backend using /verifyReceipt
+            // - Debug and sandbox builds (potentially using StoreKit config files):
+            //      We need to always refresh the receipt because the backend might not use /verifyReceipt
```
Comment (aboedo) [inline Sources/Purchasing/Purchases/PurchasesOrchestrator.swift:790]: let's specify that the backend will not use `/verifyReceipt` when the receipt was generated locally with StoreKitTest / StoreKit Configuration files

**Review by aboedo — APPROVED** [review]

File: Sources/Purchasing/Purchases/PurchasesOrchestrator.swift (hunk 1 above)
Comment (NachoSoto) [reply Sources/Purchasing/Purchases/PurchasesOrchestrator.swift:790]: Done.
