### PR TITLE
Fix Xcode 15 warning for main actor-isolated background task calls

### LINKED ISSUE #6248: 🐛 Call to main actor-isolated instance method 'beginBackgroundTask(withName:expirationHandler:)' in a synchronous nonisolated context
### Describe the bug

I use Xcode 15.2. I set concurrency checks to minimal in my build settings. I use Swift Language Version 5, and have these other settings: Build Libraries for Distribution = NO, Validate Build Product = NO.                           
The error in the title of my issue report is being caused by this code in private extension EventsManager in EventsManager.swift:     static func beginBackgroundTask(named taskName: String) -> (@Sendable () -> Void)? {
        guard let application = SystemInfo.sharedUIApplication else {
            Logger.warn(EventsManagerStrings.background_task_unavailable)
            return nil
        }

        let backgroundTaskID: Atomic<UIBackgroundTaskIdentifier?> = .init(nil)
        backgroundTaskID.value   = application.beginBackgroundTask(withName: taskName) {
            Logger.warn(EventsManagerStrings.background_task_expired(taskName))
            if let taskID = backgroundTaskID.value {
                application.endBackgroundTask(taskID)
                backgroundTaskID.value = .invalid
            }
        }

        if backgroundTaskID.value == .invalid {
            Logger.warn(EventsManagerStrings.background_task_failed(taskName))
            return nil
        }

        Logger.debug(EventsManagerStrings.background_task_started(taskName))
        return {
            if let taskID = backgroundTaskID.value {
                application.endBackgroundTask(taskID)
            }
        }
    } 

### Platform

iOS

### SDK version

5.58.0

### SDK integration method

Swift Package Manager

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

macOS 14.3.1

### Xcode version

15.2

### Device and/or simulator

Device

### Environment

Sandbox

### How widespread is the issue

100

### Debug logs

```shell
Call to main actor-isolated instance method 'endBackgroundTask' in a synchronous nonisolated context

Call to main actor-isolated instance method 'beginBackgroundTask(withName:expirationHandler:)' in a synchronous nonisolated context
```

### Steps to reproduce

I was trying to build the code

### Other information

```markdown

```

### Additional context

```markdown

```

### PR DESCRIPTION
**Pull request by ajpallares**
### Motivation
Resolves #6248

Building with Xcode 15 (Swift 5.9 compiler) produces warnings when calling `beginBackgroundTask` and `endBackgroundTask` from a `nonisolated` context, because those `UIApplication` methods are `@MainActor`-isolated in Xcode 15 or older and the calling context is `nonisolated` (more details [here](https://github.com/RevenueCat/purchases-ios/issues/6248#issuecomment-3890580335)).

The existing guard used `#if swift(>=5.9)`, which checks the *language version* the code is compiled with — not the *compiler version*. This meant the background task code was still compiled on the Swift 5.9 compiler, where the warning is emitted.

### Description
- Changed `#if swift(>=5.9)` to `#if compiler(>=6)` for background task calls in `EventsManager`, so the code is only compiled when using a Swift 6+ compiler (Xcode 16+), where these APIs are actually `nonisolated`.
- This eliminates the warning for users building with Xcode 15 while preserving the background task behavior on newer compilers.

### CODE REVIEW

**Comment by ajpallares** [comment]
@RCGitBot please test

File: Sources/Events/EventsManager.swift [hunk 1]
```diff
@@ -232,7 +232,7 @@ private extension EventsManager {
     }
 
     nonisolated func withBackgroundTask(name: String, do work: @escaping () async -> Void) {
-        #if swift(>=5.9) && (os(iOS) || os(tvOS) || VISION_OS)
+        #if swift(>=6) && (os(iOS) || os(tvOS) || VISION_OS)
         let endBackgroundTask: (() -> Void)?
```
Comment (rickvdl) [inline Sources/Events/EventsManager.swift:236]: This does mean we're removing background task support for Swift 5.9 users right? Wouldn't that be an issue?

Could we work around this by doing a 5.9 specific `@preconcurrency import UIKit` maybe?

Comment (ajpallares) [reply Sources/Events/EventsManager.swift:236]: Oh right! I actually got confused with the `#if compiler(>=6)` check 🤦‍♂️ 

I'll rethink this. Good catch!

Comment (ajpallares) [reply Sources/Events/EventsManager.swift:236]: In fact, I was checking the original PR where I added this https://github.com/RevenueCat/purchases-ios/pull/5932 and I talked about "compiler" where I still wrote `#if swift` 🤦‍♂️ 
So it looks like I was confused by this back then as well.


image

And I mentioned that `beginBackgroundTask` was marked as `@MainActor` in previous versions of the compiler to 5.9, but that was also wrong. Compiler 5.9 was still marked as `@MainActor` (or rather, it was not marked with `nonisolated`), so the correct check was `#if compiler(>=6)` all along!

Comment (ajpallares) [reply Sources/Events/EventsManager.swift:236]: Fixed in https://github.com/RevenueCat/purchases-ios/pull/6251/commits/848af4762dfeff951854d4d937e64bdc0e2fe14f. Thanks again @rickvdl!

**Comment by ajpallares** [comment]
@RCGitBot please test
