### PR TITLE
[EXTERNAL] fix: dont show video in now playing (control center/lock screen)

### LINKED ISSUE #6006: 🐛 iOS video playback, shows the video controls in "Now Playing" (lock screen/control center)
### Describe the bug

While viewing a paywall with a background video, lock your device or open the control center, you can see the paywall video's controls like play pause etc. Paywall video controls should not appear on control center and lock screen.

### Platform

iOS

### SDK version

5.53.0

### SDK integration method

CocoaPods

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 26.1

### Xcode version

16.4

### Device and/or simulator

Device

### Environment

TestFlight

### How widespread is the issue

100%

### Debug logs

```shell
No logs needed.
```

### Steps to reproduce

1. Create a paywall that has background video
2. Navigate to Revenuecat's official app or your own app for preview
3. View the paywall
4. Lock your device / open control center
5. See your app's name with video controls (play/pause)

### Other information

```markdown

```

### Additional context

```markdown
I have discovered this issue while using react-native-purchases and react-native-purchases-ui sdk's, both of them in latest `9.6.13` version. Issue also seems to be affecting RevenueCat's iOS app.
```

### PR DESCRIPTION
**Pull request by erenkulaksiz**
### Checklist
- [ ] If applicable, unit tests
- [ ] If applicable, create follow-up issues for `purchases-android` and hybrids

### Motivation

Resolves #6006 

### Description

I have observed that media also could be viewed in Dynamic Island.

Set `preventsDisplaySleepDuringVideoPlayback`, `allowsExternalPlayback` to false, to make sure the media doesnt show up in now playing.

Used ambient category for AVAudioSession, making it so that it doesnt block other audio while video is playing. 

On AVPlayerViewController, set `allowsPictureInPicturePlayback` to false, to make sure this media cant be played elsewhere.

Old pr: #6009

### CODE REVIEW

File: RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift [hunk 1]
```diff
@@ -50,6 +50,14 @@ struct VideoPlayerUIView: UIViewControllerRepresentable {
         }
 
         avPlayer.isMuted = muteAudio
+        avPlayer.preventsDisplaySleepDuringVideoPlayback = false
+        avPlayer.allowsExternalPlayback = false
+
+        try? AVAudioSession.sharedInstance().setCategory(
+            .ambient,
+            mode: .default,
+            options: [.mixWithOthers]
```
Comment (facumenzella) [inline RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: Let's store the previous category, so we can restore it later.

File: RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift [hunk 2]
```diff
@@ -50,6 +50,14 @@ struct VideoPlayerUIView: UIViewControllerRepresentable {
...
+        )
```
Comment (facumenzella) [inline RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: Let's try-catch this like:

```
  do {                                                                                                                                 
      try AVAudioSession.sharedInstance().setCategory(                                                                                 
          .ambient,                                                                                                                    
          mode: .default,                                                                                                              
          options: [.mixWithOthers]                                                                                                    
      )                                                                                                                                
  } catch {                                                                                                                            
      Logger.warn(                                                                                                                     
          PaywallStrings...                           
      )                                                                                                                                
  }     
```
