### PR TITLE
[Paywalls V2] Fix video performance in multi-page carousels

### LINKED ISSUE #6150: [Paywalls v2] Multi-page carousel with video content causing UI freezes/lag or failure to load
### Describe the bug

Multi-page carousels showing videos on each page causes performance issues ranging from severe UI freezes to complete failure to load. The behavior is inconsistent even on the same device:

**Failure mode 1 - UI freeze:** App becomes completely unresponsive for 30+ seconds while videos load. They eventually play.

**Failure mode 2 - Silent failure:** Paywall loads quickly and remains responsive, but videos never display (render as blank black squares).

Tested on:
- iPhone Xr (iOS 18.7.3): Both failure modes observed
- iPhone 14 (iOS 26): Videos load slowly with noticeable UI lag
- iPhone 17 simulator (iOS 26): Both failure modes observed

A single-page carousel with the same video configuration works correctly in all cases.

The paywall is configured via the RevenueCat dashboard using Paywalls v2's custom paywall builder. Videos are set to autoplay, looped, with muted audio.

### Platform

iOS

### SDK version

5.56.0

### SDK integration method

Swift Package Manager

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 18.7.3 and iOS 26

### Xcode version

26.2

### Device and/or simulator

Device

### Environment

Sandbox

### How widespread is the issue

100% reproducible on multi-page carousels with video content

### Debug logs

```shell
No errors observed in logs. Happy to capture verbose logs if needed.
```

### Steps to reproduce

1. Create a Paywalls v2 paywall using the RevenueCat dashboard's custom paywall builder
2. Add a carousel component with 2+ pages
3. Set each page's featured content to a video (autoplay enabled, looped, muted)
4. Present the paywall on iOS

**Expected behavior:** Videos load asynchronously without blocking the UI and autoplay reliably.

**Actual behavior:** Inconsistent, even on the same device—either the UI freezes for 30+ seconds until videos load, OR the paywall loads quickly but videos remain as blank black squares indefinitely.

### Other information

```markdown
Related issue: Android exhibits different but also problematic behavior with carousel videos: https://github.com/RevenueCat/purchases-android/issues/3058
```

### Additional context

```markdown
- Single-page carousels work correctly; issue only manifests with multiple pages
- Both failure modes can occur on the same device, suggesting a race condition rather than a device capability issue
- Happy to share a link to my paywall configuration if helpful
```

### PR DESCRIPTION
**Pull request by facumenzella**
## Motivation / Description

Fixes #6150

Multi-page carousels with video content were causing UI freezes and failures to load because multiple `AVPlayer` instances were being created simultaneously and competing for resources.

## Changes introduced

- **New `CarouselState` environment object**: Tracks carousel pagination state (active index, page index, original count) and exposes computed properties `isActive` and `isActiveOrNeighbor`
- **Lazy video player creation**: `VideoComponentView` now only creates `AVPlayer` instances for active and adjacent pages, preventing resource contention
- **Improved fallback behavior**: The fallback image now always renders as a background layer, with video overlaying once ready
- **Scroll gesture fix**: Disabled user interaction on video player view when controls are hidden to allow carousel swipe gestures to pass through

### CODE REVIEW

File: RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift [hunk 1]
```diff
@@ -38,11 +38,20 @@ struct VideoComponentView: View {
...
+
     @State var size: CGSize = .zero
 
     @State private var cachedURL: URL?
     @State var imageSource: PaywallComponent.ThemeImageUrls?
 
+    /// Tracks whether this page is active or adjacent. Updated via onChange to ensure SwiftUI detects the change.
+    @State private var isPlayable: Bool = true
+
+    /// Forces player recreation only when becoming playable (to keep autoplay reliable without churn).
```
Comment (vegaro) [inline RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift]: I don't fully understand this and the name of the variable

File: RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift [hunk 2]
```diff
@@ -162,6 +179,12 @@ struct VideoComponentView: View {
                 }
             }
             .onSizeChange { size = $0 }
+            .onAppear {
+                updatePlayableState(isPlayable: carouselState?.isActiveOrNeighbor ?? true)
+            }
+            .onChange(of: carouselState) { newState in
```
Comment (vegaro) [inline RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift]: It looks like this one is deprecated? why do you need both versions?

File: RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift [hunk 3]
```diff
@@ -97,9 +97,14 @@ struct VideoPlayerUIView: UIViewControllerRepresentable {
         controller.player = player
         controller.view.backgroundColor = .clear
         controller.showsPlaybackControls = showControls
+        // Disable user interaction when controls are hidden to allow scroll gestures to pass through
```
Comment (vegaro) [inline RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: what happens when controls are shown? does it work? or it won't scroll the carousel

Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Video/VideoPlayerViewUIView.swift]: - when controls are shown (editor setting sadly), users can interact with video
- when hidden, carousel swipes work when swiping from the video

File: RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift (hunk 2 above)
Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift]: Changed from `onChange(of:)` to `onChangeOf` helper

File: RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift (hunk 1 above)
Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift]: Renamed to `playerRefreshToggle` with clearer documentation

**Comment by facumenzella** [comment]
@vegaro I'll re-test all this once https://github.com/RevenueCat/purchases-ios/pull/6186 is merged

**Comment by facumenzella** [comment]
@vegaro can you take another look? I think it's ready :)

File: RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift [hunk 4]
```diff
@@ -214,10 +214,18 @@ private struct CarouselView<Content: View>: View {
                 )
             }
 
-            // Main horizontal “strip” of pages:
+            // Main horizontal "strip" of pages:
             HStack(alignment: self.pageAlignment, spacing: spacing) {
-                ForEach(data) { item in
+                ForEach(Array(data.enumerated()), id: \.element.id) { pageIndex, item in
```
Comment (vegaro) [inline RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift:219]: Is this creating one `CarouselState` per page every time the Carousel is rendered (every swipe)?

Comment (facumenzella) [reply RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift:219]: Technically it does on each render, but this is fine:
- It's a lightweight struct
- It's pretty standard on SwiftUI. Child views will only be affected when there's a change

**Comment by facumenzella** [comment]
not crying, you're crying @vegaro
