### PR TITLE
Detect ErrorCode.productAlreadyPurchasedError when SKError.unknown is actually cased by it

### LINKED ISSUE #392: Attempts to subscribe to an existing subscription are reported as `.storeProblemError` with a message of "An unknown error occurred".
Attempts to subscribe to an existing subscription are reported as `.storeProblemError` with a message of "An unknown error occurred".

> PaymentQueue removedTransaction: appname (null) ((null) Error Domain=SKErrorDomain Code=0 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred, NSUnderlyingError=0x282e3ee50 {Error Domain=ASDServerErrorDomain Code=3532 "You’re currently subscribed to this." UserInfo={NSLocalizedDescription=You’re currently subscribed to this.}}}) {
    NSLocalizedDescription = "An unknown error occurred";
    NSUnderlyingError = "Error Domain=ASDServerErrorDomain Code=3532 \"You\U2019re currently subscribed to this.\" UserInfo={NSLocalizedDescription=You\U2019re currently subscribed to this.}";

To reproduce:

- Purchase some subscription with a sandbox user
- Try to purchase that same subscription
- An alert box will be presented with the title "You're current subscribed to this" with alert actions of "Manage | OK"
- Pressing OK eventually results in the console log output above

This is a problem because this handling of this error is different than other kinds of store errors, as described in https://docs.revenuecat.com/docs/errors#--store_problem, and this purchase request will not or should not be retried.

- Purchases v3.7.6
- iOS 14.0
- Sandbox

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #392.

As per the conversation in that issue, this introspects and checks for the undocumented error domain and code.

### CODE REVIEW

File: PurchasesTests/Purchasing/PurchasesTests.swift [hunk 1]
```diff
@@ -2112,6 +2112,45 @@ class PurchasesTests: XCTestCase {
         expect(receivedUserCancelled).toEventually(beFalse())
     }
 
+    func testUnknownErrorCurrentlySubscribedIsParsedCorrectly() {
```
Comment (taquitos) [inline PurchasesTests/Purchasing/PurchasesTests.swift:2115]: Yessss tests are the bests

**Review by taquitos — APPROVED** [review]
🎛 🐐

File: Purchases/Error Handling/ErrorUtils.swift [hunk 2]
```diff
@@ -240,6 +240,19 @@ private extension SKError {
              .overlayInvalidConfiguration,
              .unsupportedPlatform:
             return .purchaseNotAllowedError
+        case .unknown:
+            if let error = self.userInfo[NSUnderlyingErrorKey] as? NSError {
+                switch (error.domain, error.code) {
+                case ("ASDServerErrorDomain", 3532): // "You’re currently subscribed to this"
+                    // See https://github.com/RevenueCat/purchases-ios/issues/392
+                    return .productAlreadyPurchasedError
```
Comment (aboedo) [inline Purchases/Error Handling/ErrorUtils.swift:248]: ❤️

**Review by aboedo — APPROVED** [review]
