### PR TITLE
`Paywalls`: always dismiss paywalls automatically after a purchase

### LINKED ISSUE #3516: Paywall with 'displayCloseButton: true' not closing automatically after successful purchase
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
See the title and steps to reproduce below.

1. Environment
   1. Platform:
   2. SDK version:
   3. StoreKit version:
      - [x] StoreKit 1
      - [ ] StoreKit 2 (_enabled with `usesStoreKit2IfAvailable(true)`_)
   4. OS version:
   5. Xcode version:
   6. Device and/or simulator:
      - [x] Device
      - [ ] Simulator
   7. Environment:
      - [x] Sandbox
      - [ ] TestFight
      - [ ] Production
   8. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue. **Complete logs with `Purchases.logLevel = .verbose` will help us debug this issue.**

```
DEBUG: ℹ️ There are no requests currently running, starting request POST /v1/receipts
DEBUG: ℹ️ API request started: POST '/v1/receipts'
DEBUG: ℹ️ API request completed: POST '/v1/receipts' (200)
DEBUG: ℹ️ PostReceiptDataOperation: Finished
INFO: 💰 Finishing transaction '2000000478682565' for product 'Premium.Yearly'
DEBUG: ℹ️ Serial request done: POST /v1/receipts, 0 requests left in the queue
DEBUG: ℹ️ StoreKit1Wrapper (0x0000000282298600) removedTransaction: Premium.Yearly 2000000478682565 2000000477229822 1
DEBUG: ℹ️ Sending updated CustomerInfo to delegate.
DEBUG: ℹ️ Detected active subscriptions changed. Clearing trial or intro eligibility cache.
DEBUG: ℹ️ PurchasedProductsFetcher: invalidating cache
INFO: 😻💰 Purchased product - 'Premium.Yearly'
```

3. Steps to reproduce, with a description of expected vs. actual behavior

* Press a button that triggers this sheet by changing `@State var showPaywall: Bool` to `true`:

```Swift
.sheet(isPresented: self.$showPaywall, onDismiss: self.loadPremiumState) {
   PaywallView(displayCloseButton: true)
}
```

* Make a purchase with Sandbox account (same issue also with "Restore" button when purchase available)
* Wait for the "Purchase successful" system alert dialog to appear
* Press "OK" on the alert

Expected: The paywall closes automatically as a purchase is finalized. Alternatively, the paywall should update to mark the purchased product as purchased and change the "Continue" button to something like "Close" or "Back". But better to simply automatically close the paywall.

Actual behavior: I'm back in the paywall and everything looks as if no purchase was made yet, confusing the user. The user has to press the "X" button at the top right to close the window, then everything works, the purchase is active. But why did the paywall not close then? Really confusing.
 
5. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
N/A

6. **Additional context**
N/A

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #3516.

This logic only existed for `.presentPaywallIfNeeded`. However, it should apply to `PaywallView` when presented manually as well.

This is also consistent with how Android works, reduces boilerplate code required by users, and removes the possibility that a paywall is still presented after a purchase, which doesn't make sense since our paywalls don't have a mode for "already subscribed".

### CODE REVIEW

File: RevenueCatUI/View+PresentPaywall.swift [hunk 1]
```diff
@@ -179,8 +179,6 @@ private struct PresentingPaywallModifier: ViewModifier {
                 )
                 .onPurchaseCompleted {
                     self.purchaseCompleted?($0)
-
-                    self.close()
```
Comment (NachoSoto) [inline RevenueCatUI/View+PresentPaywall.swift:183]: This is done by `PaywallView` automatically now.

**Review by tonidero — APPROVED** [review]

File: RevenueCatUI/PaywallView.swift [hunk 2]
```diff
@@ -305,14 +302,19 @@ struct LoadedOfferingPaywallView: View {
             .disabled(self.purchaseHandler.actionInProgress)
             .onAppear { self.purchaseHandler.trackPaywallImpression(self.createEventData()) }
             .onDisappear { self.purchaseHandler.trackPaywallClose() }
+            .onChangeOf(self.purchaseHandler.purchased) { purchased in
+                if purchased {
+                    Logger.debug(Strings.dismissing_paywall)
+                    self.dismiss()
```
Comment (tonidero) [inline RevenueCatUI/PaywallView.swift:308]: I wonder if this could be considered a breaking change somewhat... Since people might have had to handle this before, would they be dismissing the paywall twice with this now?

Comment (NachoSoto) [reply RevenueCatUI/PaywallView.swift:308]: Even if they do, I tested it and there is no difference :) The double-dismissal becomes a no-op.
