### PR TITLE
Fixes `SubscriptionDetailsView` background color in dark mode

### LINKED ISSUE #4335: CustomerCenter Dark mode colors looks off
- [x ] I have updated Purchases SDK to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [ x] I have searched the [Community](https://community.revenuecat.com)
- [ x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: iOS
   2. SDK version: 5.5.0
   3. StoreKit version:
      - [ ] StoreKit 1 (default on versions <5.0.0. Can be enabled in versions >=5.0.0 with `.with(storeKitVersion: .storeKit1)`)
      - [x] StoreKit 2 (default on versions >=5.0.0)
   4. OS version: 18.0
   5. Xcode version: 16.0
   6. Device and/or simulator:
      - [x ] Device
      - [ ] Simulator
   7. Environment:
      - [x ] Sandbox
      - [ ] TestFlight
      - [ ] Production
   8. How widespread is the issue. Percentage of devices affected.

3. Steps to reproduce, with a description of expected vs. actual behavior

Open Customer Center in dark mode, the text is next to the gray background, on light mode there are not 2 different colors for the background, so it does not look too bad

IMG_AFD8DDBBF966-1

As additional feedback, when the user touches the offer button to accept the offer, there is a delay between the tap until something happens. First time I tested though that nothing was happening, then the offer in app purchase just keeps popping up all the time, kind of looking like a bug.

Maybe a loading should be implemented,  but for sure the button should be disable for touching multiple times, that way the in app purchase is not going to pop up multiple times.

### PR DESCRIPTION
**Pull request by JayShortway**
## Bug
The `SubscriptionDetailsView` has 2 different background colors in dark mode.

## Fix
The fix is to remove the entire background color from `SubscriptionDetailsView`. The `Section` in which the `SubscriptionDetailsView` is placed by `ManageSubscriptionsView` already sets the correct background color. 

## Also
Added dark mode previews to `SubscriptionDetailsView` and `ManageSubscriptionsView` to more easily catch these issues.

## Reference image
image

Closes #4335.

### CODE REVIEW

File: RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift [hunk 1]
```diff
@@ -122,7 +122,6 @@ struct SubscriptionDetailsView: View {
 
         }
         .padding(.vertical, 8.0)
-        .background(Color(UIColor.tertiarySystemBackground))
```
Comment (JayShortway) [inline RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift:125]: For visibility, this is the actual fix haha.

**Review by vegaro — APPROVED** [review]
