### PR TITLE
`Paywalls`: prioritize `Locale.current` over `Locale.preferredLocales`

### LINKED ISSUE #3655: Paywall shows in English despite iPhone being set to German
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
I have a Paywall defined, and a "German (Germany)" localization defined for it. I have an iOS SwiftUI app with the latest SDK (4.36.0). I run it on a phone with "German" (not "German (Germany)") set as the top language, English as the second, then a variety of others. When I view the Paywall, it opens with my strings in English, but the default RevenueCat-supplied strings in German (ie. "Restore", "Privacy Policy", etc at the bottom). If I change it so "German (Germany)" is top, it displays all strings in German.

By the way, I am physically located in Switzerland, so even when I select just "German" from the language list without a country specifier, the phone sets the country of my locale to "CH" automatically.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.36.0
   3. StoreKit version:
      - [x] StoreKit 1
      - [ ] StoreKit 2 (_enabled with `usesStoreKit2IfAvailable(true)`_)
   4. OS version: 17.2.1
   5. Xcode version: 15.2
   6. Device and/or simulator:
      - [X] Device
      - [X] Simulator (does not happen on 15.5 on simulator, but does on 16.4 and 17.2)
   7. Environment:
      - [X] Sandbox
      - [ ] TestFight
      - [ ] Production
   8. How widespread is the issue. Percentage of devices affected. 100% reproducible on all devices and iOS 17.2 simulators I've tested... also tried physical iPad and some other physical test devices.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue. **Complete logs with `Purchases.logLevel = .verbose` will help us debug this issue.**

```
 - <AppMeasurement>[I-ACS036001] Analytics screen reporting is disabled. UIViewController transitions will not be logged.
10.21.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001011] App Delegate Proxy is disabled.
10.21.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.21.0 started
10.21.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
10.21.0 - [FirebaseAnalytics][I-ACS025036] App Delegate Proxy is disabled
DEBUG: ℹ️ Configuring SDK using RevenueCat's UserDefaults suite.
VERBOSE: DeviceCache.init: DeviceCache (0x0000000282138a20)
VERBOSE: StoreKit1Wrapper.init: StoreKit1Wrapper (0x0000000282138f00)
DEBUG: 👤 Identifying App User ID
VERBOSE: Initializing PaywallEventStore: file:///var/mobile/Containers/Data/Application/DC949E39-05F5-4977-9C2B-0BE6E60C945C/Library/Application%20Support/revenuecat/paywall_event_store
VERBOSE: Creating FileHandler for: file:///var/mobile/Containers/Data/Application/DC949E39-05F5-4977-9C2B-0BE6E60C945C/Library/Application%20Support/revenuecat/paywall_event_store
VERBOSE: PaywallEventsManager initialized
VERBOSE: PurchasesOrchestrator.init: PurchasesOrchestrator (0x000000010470e5e0)
DEBUG: ℹ️ Debug logging enabled
DEBUG: ℹ️ SDK Version - 4.36.0
DEBUG: ℹ️ Bundle ID - com.aardustry.BriefLook
DEBUG: ℹ️ System Version - Version 17.2.1 (Build 21C66)
DEBUG: ℹ️ Not using a simulator.
DEBUG: 👤 No initial App User ID
DEBUG: ℹ️ Purchases is configured with response verification disabled
VERBOSE: Purchases.init: created new Purchases instance: Purchases (0x000000010470e780)
StoreKit Wrapper: left(<RevenueCat.StoreKit1Wrapper: 0x282138f00>)
DEBUG: ℹ️ Delegate set
DEBUG: ℹ️ applicationWillEnterForeground
DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
DEBUG: ℹ️ Offerings cache is stale, updating from network in foreground
VERBOSE: Enqueing network operation 'GetOfferingsOperation' with cache key: 'GetOfferingsOperation REDACTED_USER_ID'
DEBUG: ℹ️ GetOfferingsOperation: Started
DEBUG: ℹ️ There are no requests currently running, starting request GET /v1/subscribers/REDACTED_USER_ID/offerings
VERBOSE: Using etag '2280cfc1dcce7d96' for request to 'https://api.revenuecat.com/v1/subscribers/REDACTED_USER_ID/offerings'. Validation time: 2024-02-07 21:56:45 +0000
DEBUG: ℹ️ API request started: GET '/v1/subscribers/REDACTED_USER_ID/offerings'
VERBOSE: Enqueing network operation 'GetCustomerInfoOperation' with cache key: 'GetCustomerInfoOperation REDACTED_USER_ID'
Anonymous authResult: <FIRAuthDataResult: 0x280504ac0>
WARN: ⚠️ The appUserID passed to logIn is the same as the one already cached. No action will be taken.
DEBUG: ℹ️ Vending CustomerInfo from cache.
VERBOSE: Updating all caches
DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'GetOfferingsOperation REDACTED_USER_ID'. Skipping request.
DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'GetCustomerInfoOperation REDACTED_USER_ID'. Skipping request.
DEBUG: ℹ️ No cached Offerings, fetching from network
User REDACTED_USER_ID signed in
DEBUG: ℹ️ CustomerInfo cache is stale, updating from network in foreground.
DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'GetOfferingsOperation REDACTED_USER_ID'. Skipping request.
DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'GetOfferingsOperation REDACTED_USER_ID'. Skipping request.
DEBUG: ℹ️ Network operation 'GetCustomerInfoOperation' found with the same cache key 'GetCustomerInfoOperation REDACTED_USER_ID'. Skipping request.
VERBOSE: Paywall event flushing requested with empty store.
10.21.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
10.21.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
VERBOSE: Storing etag '2280cfc1dcce7d96' for request to 'https://api.revenuecat.com/v1/subscribers/REDACTED_USER_ID/offerings' (success)
DEBUG: ℹ️ API request completed: GET '/v1/subscribers/REDACTED_USER_ID/offerings' (304)
Request-ID: '4aca8d4b-7673-4b8a-b954-a34ab0a865c0'; Amzn-Trace-ID: 'Root=1-65c40d45-5960625c6b11334a65a3c32a'
DEBUG: ℹ️ No existing products cached, starting store products request for: ["REDACTED_PRODUCT_ID"]
DEBUG: ℹ️ Found an existing request for products: ["REDACTED_PRODUCT_ID"], appending to completion
DEBUG: ℹ️ Found an existing request for products: ["REDACTED_PRODUCT_ID"], appending to completion
DEBUG: ℹ️ Found an existing request for products: ["REDACTED_PRODUCT_ID"], appending to completion
DEBUG: ℹ️ GetOfferingsOperation: Finished
DEBUG: ℹ️ Serial request done: GET /v1/subscribers/REDACTED_USER_ID/offerings, 0 requests left in the queue
DEBUG: ℹ️ GetCustomerInfoOperation: Started
DEBUG: ℹ️ There are no requests currently running, starting request GET /v1/subscribers/REDACTED_USER_ID
VERBOSE: Using etag '0d94a5f4303b67f3' for request to 'https://api.revenuecat.com/v1/subscribers/REDACTED_USER_ID'. Validation time: 2024-02-07 21:56:46 +0000
DEBUG: ℹ️ API request started: GET '/v1/subscribers/REDACTED_USER_ID'
VERBOSE: Storing etag '0d94a5f4303b67f3' for request to 'https://api.revenuecat.com/v1/subscribers/REDACTED_USER_ID' (success)
DEBUG: ℹ️ API request completed: GET '/v1/subscribers/REDACTED_USER_ID' (304)
Request-ID: 'a838d02e-5260-4ba2-b4cc-46478a661e8d'; Amzn-Trace-ID: 'Root=1-65c40d45-5885d9060a81dcff42670a92'
VERBOSE: Updating CustomerInfo 'REDACTED_RC_USER_ID' request date: 2024-02-07 23:07:49 +0000
DEBUG: 😻 CustomerInfo updated from network.
DEBUG: 😻 CustomerInfo updated from network.
DEBUG: 😻 CustomerInfo updated from network.
DEBUG: ℹ️ GetCustomerInfoOperation: Finished
DEBUG: ℹ️ Serial request done: GET /v1/subscribers/REDACTED_USER_ID, 0 requests left in the queue
DEBUG: 😻 Store products request finished
DEBUG: 😻 Store products request received response
DEBUG: 😻 Offerings updated from network.
DEBUG: 😻 Offerings updated from network.
DEBUG: ℹ️ Warming up intro eligibility cache for 1 products
DEBUG: 😻 Offerings updated from network.
DEBUG: 😻 Offerings updated from network.
WARN: 🍎‼️ Unable to load receipt, ensure you are logged in to a valid Apple account.
Error: Error Domain=NSCocoaErrorDomain Code=260 "Die Datei „sandboxReceipt“ konnte nicht geöffnet werden, da sie nicht existiert." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/DC949E39-05F5-4977-9C2B-0BE6E60C945C/StoreKit/sandboxReceipt, NSUnderlyingError=0x280bba7c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
DEBUG: ℹ️ Skipping products request for these products because they were already cached: ["REDACTED_PRODUCT_ID"]
DEBUG: ℹ️ Caching trial or intro eligibility for products: ["REDACTED_PRODUCT_ID"]
VERBOSE: Warming up paywall images cache: [https://assets.pawwalls.com/1005196_1706798838.heic]
Using adUnitID REDACTED_GOOGLE_ADUNIT_ID
<UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"REDACTED_DEVICE_ID" ];
10.21.0 - [FirebaseAnalytics][I-ACS025026] Deferring to Firebase for event data collection
<Google> To get test ads on this device, set: 
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"REDACTED_DEVICE_ID" ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ "REDACTED_DEVICE_ID" ]
WebContent process (0x121018680) took 2.939819 seconds to launch
VERBOSE: PurchasesOrchestrator: caching presented paywall
VERBOSE: Storing event: impression(RevenueCat.PaywallEvent.CreationData(id: 6D511A09-2A08-464D-A2D9-84A38D001DD2, date: 2024-02-07 23:08:01 +0000), RevenueCat.PaywallEvent.Data(offeringIdentifier: "default", paywallRevision: 17, sessionIdentifier: 523B3FD6-4266-42AF-83CC-BD63DFCA9432, displayMode: RevenueCat.PaywallViewMode.fullScreen, localeIdentifier: "de_CH", darkMode: true))
VERBOSE: Starting request for image: 'https://assets.pawwalls.com/1005196_1706798838.heic'
DEBUG: ℹ️ Found cached trial or intro eligibility for products: ["REDACTED_PRODUCT_ID"]
VERBOSE: Successfully loaded image
```

3. Steps to reproduce, with a description of expected vs. actual behavior

	1. Define an English Paywall in RevenueCat
	2. Localize the Paywall to "German (Germany)" (the only German option RevenueCat offers)
	3. Create a SwiftUI app with English and German localizations in XCode
	4. Create a Paywall as per the RevenueCat docs with PaywallView(displayCloseButton: true) 
	5. Run it on an iPhone (I'm using my iPhone 13 Pro) Edit to Add: If this is significant, run it on a phone physically sitting in Switzerland.
	6. Set the iPhone to English first, German second (note: not "German (Germany)" or "German (Switzerland)", but "German")
	7. Note that the Paywall comes up in English.
	8. Set the iPhone to German first, English second (note: not "German (Germany)" or "German (Switzerland)")
	9. (incorrect) Kill and relaunch the app. Note the Paywall comes up with the user-supplied strings in English, but the RevenueCat strings ("Restore", "Privacy Policy", etc) translated to German.
	10. Set the iPhone to "German (Germany)"
	11. Kill and relaunch the app. Note the Paywall comes up in German-- both the user-supplied translation and the RevenueCat-supplied strings.
 
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

I pulled some of the code out of the latest PaywallData+Localization.swift and Locale+Extensions.swift and copied it into my app in order to see what the locale list would be. So this code imitates the portion of the RevenueCat code which pulls the language list:
```Swift
    print("Preferred Locale: \(Locale.preferredLanguages.first ?? "unknown")")
    print("App Locale: \(Locale.current.identifier)")
    if #available(iOS 16, *) {
      let languageCode = Locale.current.language.languageCode?.identifier
      print("App languageCode: \(languageCode ?? "unknown")")
      let removingRegion = languageCode.map(Locale.init(identifier:))
      print("altLocale identifer: \(removingRegion?.identifier ?? "unknown")")
      print("altLocale language identifier: \(removingRegion?.language.languageCode?.identifier ?? "unknown")")
      let preferredLocales = Locale.preferredLanguages.map(Locale.init(identifier:))
      var result = [.current] + preferredLocales
      if let withoutRegion = removingRegion {
          result.append(withoutRegion)
      }
      print("preferred language list: \(result)")
    }
```

When run in my app, it outputs the following (note I've been doing a lot of localization testing on this phone, so it has many languages, but this is reproducible on a phone with just German and English):
```
Preferred Locale: de-CH
App Locale: de_CH
App languageCode: de
altLocale identifer: de
altLocale language identifier: de
preferred language list: [de_CH (fixed), de-CH (fixed), en-US (fixed), fr-CH (fixed), it-CH (fixed), es-CH (fixed), gsw-CH (fixed), de (fixed)]
```

6. **Additional context**

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #3655.
Follow up to #3633.

This improves upon that PR by using `Locale.current.removingRegion` for each locale **before** trying to look up `Locale.preferredLocales`.

This fixes this scenario:
- Configure your phone with: `en_IN` and `es_ES`
- Launch paywall with localization `en_US` and `es_ES`

Prior to this change, we'd be looking up localizations in this order:
- `en_IN`
- `es_ES`
- `en` (no region)

Because there _is_ a localization for `es_ES` we'd return that one before attempting to look up `Locale.current.removingRegion`.

Example of the new log:
> VERBOSE: Looking up localized configuration for ["en_IN", "es_ES"], searching for ["en_IN", "en", "es_ES", "es"]
> VERBOSE: Found localized configuration for 'en'

### CODE REVIEW

**Comment by samkass** [comment]
This looks like it will likely fix my issue #3655. But I think an optimal solution would be to add the removingRegion for EACH locale in the list, and try it right after the full locale is attempted. So [de-CH, en-UK, it-IT] becomes [de-CH, de, en-UK, en, it-IT, it]. That way, if you had a US English and an Italian localization, it would pick up the English one in the above example based on the UK English preference.

**Comment by NachoSoto** [comment]
That makes sense, I'll make that change 👍🏻

**Comment by NachoSoto** [comment]
@samkass updated. We'll release this on the next 4.x release this week 👍🏻

File: Sources/Paywalls/PaywallData+Localization.swift [hunk 1]
```diff
@@ -50,13 +53,7 @@ public extension PaywallData {
...
     /// Includes `Locale.current` and `Locale.preferredLanguages`.
     internal static var localesOrderedByPriority: [Locale] {
-        var result = [.current] + Locale.preferredLocales
-
-        if let withoutRegion = Locale.current.removingRegion {
-            result.append(withoutRegion)
-        }
-
-        return result
+        return [.current] + Locale.preferredLocales
```
Comment (NachoSoto) [inline Sources/Paywalls/PaywallData+Localization.swift:56]: This goes back to the original implementation. It allows us to test the actual behavior in `localizedConfiguration` since it no longer relies on this returning the `.removingRegion` addition.

File: Sources/Paywalls/PaywallData+Localization.swift [hunk 2]
```diff
@@ -22,8 +22,13 @@ public extension PaywallData {
     }
 
     // Visible for testing
-    internal func localizedConfiguration(for locales: [Locale]) -> LocalizedConfiguration {
-        Logger.verbose(Strings.paywalls.looking_up_localization(locales))
+    internal func localizedConfiguration(for preferredLocales: [Locale]) -> LocalizedConfiguration {
+        // Allows us to search each locale in order of priority, both with the region and without.
+        // Example: [en_UK, es_ES] => [en_UK, en, es_ES, es]
```
Comment (tonidero) [inline Sources/Paywalls/PaywallData+Localization.swift:27]: 🙌 Makes sense!

**Review by tonidero — APPROVED** [review]
