### PR TITLE
`NonSubscriptionTransaction`: expose `storeTransactionIdentifier`

### LINKED ISSUE #3636: NonSubscriptionTransaction.transactionIdentifier Does not match StoreTransaction.identifier
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
I'm trying to add consumable purchases using the guide suggested in [the docs](https://www.revenuecat.com/docs/non-subscriptions). On purchase of the product, in a final check step, I want to check to ensure that RevenueCat has processed the transaction and has added it to the user's `CustomerInfo` object.

However on purchase of the consumable, the `id/tranasctionIdentifier` of the returned `StoreTransaction` from the `Purchases.shared.purchase(package:)` does not match the `NonSubscriptionTransaction` of the `CustomerInfo.nonSubscriptions`. This leaves us with no way of checking that the transactionId is valid or reflected in RevenueCat.

Looking into the `NonSubscriptionTransaction`, it has an `internal storeTransactionIdentifier` and this does match the `StoreTransaction.id` but because it's internal, it can't be used.

Can we make the `NonSubscriptionTransaction .storeTransactionIdentifier` public? If not, please can you advise on the best approach to achieve this check.

1. Environment
   1. Platform: iOS
   2. SDK version: 4.35.0
   3. StoreKit version:
      - [x] StoreKit 1
      - [ ] StoreKit 2 (_enabled with `usesStoreKit2IfAvailable(true)`_)
   4. OS version: 14.3
   5. Xcode version: 15.2
   6. Device and/or simulator:
      - [x] Device
      - [x] Simulator
   7. Environment:
      - [x] Sandbox
      - [x] TestFight
      - [ ] Production
   8. How widespread is the issue. Percentage of devices affected.

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue. **Complete logs with `Purchases.logLevel = .verbose` will help us debug this issue.**

```
(lldb) po transaction
<StoreTransaction:
    identifier="2"
    product="dream_dev_creation_premium"
    date="2024-02-06 02:29:12 +0000"
    quantity=1
>

vs

<NonSubscriptionTransaction:
    productIdentifier=dream_dev_creation_premium
    purchaseDate=2024-02-06 02:29:12 +0000
    transactionIdentifier=38f13a6667
    storeTransactionIdentifier=2
>
```

3. Steps to reproduce, with a description of expected vs. actual behavior

* Purchase a consumable product
* Try to check the returned `StoreTransaction.id` is contained in the `customerInfo.nonSubscription` using:
```swift
customerInfo.nonSubscriptions.first(
            where: { $0.productIdentifier == transaction.productIdentifier && $0.transactionIdentifier == transaction.transactionIdentifier }
```

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
N/A

5. **Additional context**
N/A

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #3636.

This was added in #3009.
It was not made `public` because it was only used for #2841, but as explained in #3636 it can be useful as `public`.

### CODE REVIEW

**Comment by NachoSoto** [comment]
@aboedo you pointed out in https://github.com/RevenueCat/purchases-ios/pull/3009#discussion_r1293977927 that you wouldn't make it `public`. Thoughts on this now?

You mentioned:
> a) we don't currently expose it for subscriptions, so maybe it's better to avoid confusion

But we do expose it when purchasing through `StoreTransaction`.

File: Sources/Purchasing/NonSubscriptionTransaction.swift [hunk 1]
```diff
@@ -32,7 +32,7 @@ public final class NonSubscriptionTransaction: NSObject {
     @objc public let transactionIdentifier: String
 
     /// The unique identifier for the transaction created by the Store.
-    @objc internal let storeTransactionIdentifier: String
+    @objc public let storeTransactionIdentifier: String
```
Comment (tonidero) [inline Sources/Purchasing/NonSubscriptionTransaction.swift:35]: I'm only slightly concerned about the confussion of having both ids... but I think it shoud be ok?

**Review by tonidero — APPROVED** [review]
Might want to wait for @aboedo's review, since he had concerns on making this public. But LGTM!

**Review by aboedo — APPROVED** [review]

**Comment by jiangdi0924** [comment]
it‘s a good idea to  expose storeTransactionIdentifier, because get  transaction id is  storeTransactionIdentifier，but customInfo cant get it， Unable to compare and verify
