### PR TITLE
fix: improve video autoplay with thumbnail fallback and fade transition

### LINKED ISSUE #6005: 🐛 iOS video playback doesnt auto-play when video download is complete
### Describe the bug

When a video is put in background of a Paywalls V2 paywall and when paywall is viewed in the first time, purchases-ios doesnt start playing the video when its ready. Instead, when you close and reopen the same paywall, it starts playing. This seems to be only affecting on first opening of the paywall, doesnt reproducable when video is cached.

### Platform

iOS

### SDK version

5.53.0 (latest)

### SDK integration method

CocoaPods

### StoreKit version

StoreKit 2 (default on versions >=5.0.0)

### OS version

iOS 26.1

### Xcode version

16.4

### Device and/or simulator

Device

### Environment

Production

### How widespread is the issue

100%

### Debug logs

```shell
No logs needed.
```

### Steps to reproduce

1. Create a paywall that has background video
2. Navigate to Revenuecat's official app or your own app for preview
3. View the paywall
4. Video is not playing, only the thumbnail is visible
5. Close the paywall, open it again
6. Video starts playing as intented on second opening

### Other information

```markdown

```

### Additional context

```markdown
I have discovered this issue while using react-native-purchases and react-native-purchases-ui sdk's, both of them in latest `9.6.13` version. Issue also seems to be affecting RevenueCat's iOS app.
```

### PR DESCRIPTION
**Pull request by facumenzella**
## Summary

Fixes a white flash that appeared when loading paywalls with video backgrounds by ensuring the thumbnail is always visible as a base layer.

## Changes

- Remove `Color.clear` placeholder that caused the white flash on first render
- Always show thumbnail as base layer using `viewModel.imageSource` as fallback before `onAppear` sets `imageSource` state
- Add 0.3s fade transition when video appears over the thumbnail

## Problem

When a paywall with a video background loaded, users would see a brief white flash because:
1. SwiftUI renders the view body **before** `onAppear` is called
2. On first render, `imageSource` was `nil` (not yet set by `onAppear`)
3. The code showed `Color.clear` as placeholder, which rendered as white

## Solution

Instead of showing `Color.clear` when nothing is ready, always render the thumbnail by falling back to `viewModel.imageSource` when the local `imageSource` state hasn't been set yet. This ensures there's always a visible image from the first render.

## Test plan

- [ ] Open paywall with video background on first launch (not cached)
- [ ] Verify no white flash appears
- [ ] Verify video fades in smoothly over thumbnail
- [ ] Test with slow network to verify thumbnail shows while video loads

Resolves #6005

### CODE REVIEW

File: RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift [hunk 1]
```diff
@@ -60,19 +60,20 @@ struct VideoComponentView: View {
                     let viewData = style.viewData(forDarkMode: colorScheme == .dark)
 
                     ZStack {
-                        if imageSource == nil && cachedURL == nil {
-                            // greedily fill space while loading occurs
-                            render(Color.clear, size: size, with: style)
-                        }
-
-                        if let imageSource, let imageViewModel = try? ImageComponentViewModel(
+                        // Always show thumbnail as base layer while video loads/prepares
```
Comment (vegaro) [inline RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift:66]: One little improvement I am doing in Android to avoid possible flashes is to render the image on top and hide it when video starts playing. In Android we were getting a black flashing because of the video renders in a TextureView. It's probably not an issue in iOS

File: RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift [hunk 2]
```diff
@@ -60,19 +60,20 @@ struct VideoComponentView: View {
                     let viewData = style.viewData(forDarkMode: colorScheme == .dark)
 
                     ZStack {
-                        if imageSource == nil && cachedURL == nil {
-                            // greedily fill space while loading occurs
-                            render(Color.clear, size: size, with: style)
```
Comment (vegaro) [inline RevenueCatUI/Templates/V2/Components/Video/VideoComponentView.swift:65]: I think this was here to make sure fixed sized videos were correctly sized, but I am not sure. I know there's a similar hack in the Image view

**Comment by facumenzella** [comment]
@vegaro Thanks for the review!

Re: image on top approach - iOS doesn't have the TextureView black flash, so video-on-top with fade works well here.

Re: `Color.clear` for sizing - good catch! Added it back as an always-rendered spacer.

**Review by vegaro — APPROVED** [review]
